/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session-check endpoint backing the SPA's AuthGate-equivalent hook.
         * @description Same response shape as the public API's `GET /api/v1/me`, deliberately — one response shape for "who am I," regardless of which surface asked.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's own todos.
         * @description Returns only the session owner's own todos, created_at descending, unpaginated — same shape and same no-pagination reasoning as `_rules/_contract/API.md`'s `GET /api/v1/todos`.
         */
        get: operations["listTodos"];
        put?: never;
        /**
         * Create a todo owned by the caller.
         * @description `owner_id` is always the resolved session owner — never accepted from the body (I1, same rule, different auth mechanism). `done` starts false. Calls `internal/domain/todo.Service.CreateTodo` directly — the same service instance and method the public API's handler calls (`_rules/_standard/ARCHITECTURE.md`'s shared-service-layer rule).
         */
        post: operations["createTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get one of the caller's own todos.
         * @description Owner-scoped (I3): another owner's id, or an id that never existed, both return `not_found` — never `forbidden`.
         */
        get: operations["getTodo"];
        put?: never;
        post?: never;
        /**
         * Delete one of the caller's own todos.
         * @description Owner-scoped, same 404 rule. Deleting an already-deleted id is also `not_found` (naturally idempotent, same as the public API).
         */
        delete: operations["deleteTodo"];
        options?: never;
        head?: never;
        /**
         * Update one of the caller's own todos.
         * @description Owner-scoped, same 404 rule as GET.
         */
        patch: operations["updateTodo"];
        trace?: never;
    };
    "/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's own non-revoked API keys.
         * @description Same response shape as `_rules/_contract/API.md`'s `GET /api/v1/keys`. Calls `internal/identity.Service.ListAPIKeys` directly — same service, same method, session-resolved owner instead of Bearer-resolved actor.
         */
        get: operations["listKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke one of the caller's own API keys.
         * @description Sets `revoked_at`. Owner-scoped, same 404 rule. Calls `internal/identity.Service.RevokeAPIKey` directly. Deliberately no `POST /keys` and no rotate endpoint anywhere on this surface — see this file's `info.description`.
         */
        delete: operations["revokeKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            handle: string;
            role: string;
            active: boolean;
        };
        Todo: {
            id: string;
            title: string;
            done: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TodoList: {
            todos: components["schemas"]["Todo"][];
        };
        ApiKey: {
            id: string;
            prefix: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        ApiKeyList: {
            keys: components["schemas"]["ApiKey"][];
        };
        CreateTodoRequest: {
            title: string;
        };
        UpdateTodoRequest: {
            title?: string;
            done?: boolean;
        };
        Error: {
            error: {
                code: string;
                message: string;
                hint?: string;
            };
        };
    };
    responses: {
        /** @description The request violates a request-shape or validation rule. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, expired, or wrong-role session cookie — same shape regardless of which check failed (I5). A behavior change from this package's own HTML `GET /` view: this JSON surface always answers 401, never a redirect (a `fetch` call can't follow a redirect the way a browser navigation does — the SPA's own AuthGate-equivalent hook is what turns a 401 into a redirect, client-side). */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unknown id, or an id that exists but isn't the caller's (I3 — absence, not permission). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in owner. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTodos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's own todos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodoList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTodoRequest"];
            };
        };
        responses: {
            /** @description The created todo. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The todo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTodoRequest"];
            };
        };
        responses: {
            /** @description The updated todo. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Todo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's own non-revoked keys. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
