// Package bffapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package bffapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateTodoRequestPriority.
const (
	CreateTodoRequestPriorityHigh   CreateTodoRequestPriority = "high"
	CreateTodoRequestPriorityLow    CreateTodoRequestPriority = "low"
	CreateTodoRequestPriorityMedium CreateTodoRequestPriority = "medium"
	CreateTodoRequestPriorityUrgent CreateTodoRequestPriority = "urgent"
)

// Valid indicates whether the value is a known member of the CreateTodoRequestPriority enum.
func (e CreateTodoRequestPriority) Valid() bool {
	switch e {
	case CreateTodoRequestPriorityHigh:
		return true
	case CreateTodoRequestPriorityLow:
		return true
	case CreateTodoRequestPriorityMedium:
		return true
	case CreateTodoRequestPriorityUrgent:
		return true
	default:
		return false
	}
}

// Defines values for TodoPriority.
const (
	TodoPriorityHigh   TodoPriority = "high"
	TodoPriorityLow    TodoPriority = "low"
	TodoPriorityMedium TodoPriority = "medium"
	TodoPriorityUrgent TodoPriority = "urgent"
)

// Valid indicates whether the value is a known member of the TodoPriority enum.
func (e TodoPriority) Valid() bool {
	switch e {
	case TodoPriorityHigh:
		return true
	case TodoPriorityLow:
		return true
	case TodoPriorityMedium:
		return true
	case TodoPriorityUrgent:
		return true
	default:
		return false
	}
}

// Defines values for TodoStatus.
const (
	Closed     TodoStatus = "closed"
	Done       TodoStatus = "done"
	InProgress TodoStatus = "in_progress"
	Open       TodoStatus = "open"
)

// Valid indicates whether the value is a known member of the TodoStatus enum.
func (e TodoStatus) Valid() bool {
	switch e {
	case Closed:
		return true
	case Done:
		return true
	case InProgress:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`
	Id        string    `json:"id"`
	Prefix    string    `json:"prefix"`
}

// ApiKeyList defines model for ApiKeyList.
type ApiKeyList struct {
	Keys []ApiKey `json:"keys"`
}

// CreateTodoEventRequest One shape covers all four client-postable `type` values (`_contract/API.md`) — cross-field validation (e.g. `body` required for `commented`, `to` required for `status_changed`) is the handler's job, not this schema's, mirroring the public API's own `CreateTodoEventRequest`. `type` is deliberately an open string, not an `enum`, so `"created"` and any other unrecognised value reach the handler's own dispatch and are rejected there (I16) — the same path, not a special case for one string.
type CreateTodoEventRequest struct {
	// Body commented — the comment text.
	Body            *string `json:"body,omitempty"`
	ClientRequestId string  `json:"clientRequestId"`

	// Field field_changed — which field `to` changes: `title` | `priority` | `dueDate`.
	Field *string `json:"field,omitempty"`

	// To status_changed — the target status (a `Todo.status` enum value; `closed` succeeds on this surface, I18). assigned — the target assignee's user id, or `null` to unassign.
	To   *string `json:"to,omitempty"`
	Type string  `json:"type"`
}

// CreateTodoRequest `additionalProperties: false` so a stray `done` (milestone-1/2/3's removed field) is a `validation_error`, not silently dropped (`_contract/API.md`). No `status` field, deliberately (mirrors the public API's own `CreateTodoRequest`) — every created todo starts `open` regardless of what a caller asks for.
type CreateTodoRequest struct {
	AssigneeId *string `json:"assigneeId,omitempty"`

	// ClientRequestId I19's idempotency key, on the `created` event this endpoint's own side effect writes — required, not optional, since `todo_events.client_request_id` is `NOT NULL UNIQUE` at the schema level for every row including `created` ones.
	ClientRequestId string                     `json:"clientRequestId"`
	DueDate         *time.Time                 `json:"dueDate,omitempty"`
	Priority        *CreateTodoRequestPriority `json:"priority,omitempty"`
	Title           string                     `json:"title"`
}

// CreateTodoRequestPriority defines model for CreateTodoRequest.Priority.
type CreateTodoRequestPriority string

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string  `json:"code"`
		Hint    *string `json:"hint,omitempty"`
		Message string  `json:"message"`
	} `json:"error"`
}

// Me defines model for Me.
type Me struct {
	Active bool   `json:"active"`
	Handle string `json:"handle"`
	Role   string `json:"role"`
}

// Todo defines model for Todo.
type Todo struct {
	// AssigneeId References a user (any role).
	AssigneeId *string   `json:"assigneeId"`
	CreatedAt  time.Time `json:"createdAt"`

	// CreatedBy milestone-4: replaces `ownerId` — attribution only, never access-scoping (GOAL.md).
	CreatedBy string        `json:"createdBy"`
	DueDate   *time.Time    `json:"dueDate"`
	Id        string        `json:"id"`
	Priority  *TodoPriority `json:"priority"`

	// Status milestone-4: replaces `done`. Fixed enum, not an owner-editable table (GOAL.md).
	Status    TodoStatus `json:"status"`
	Title     string     `json:"title"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

// TodoPriority defines model for Todo.Priority.
type TodoPriority string

// TodoStatus milestone-4: replaces `done`. Fixed enum, not an owner-editable table (GOAL.md).
type TodoStatus string

// TodoEvent defines model for TodoEvent.
type TodoEvent struct {
	ActorId string `json:"actorId"`

	// Body The comment text for `type: commented`, `null` otherwise. Rendered client-side through a Markdown-to-React-elements path, never raw HTML (I8's mirror, GOAL.md).
	Body            *string   `json:"body,omitempty"`
	ClientRequestId string    `json:"clientRequestId"`
	CreatedAt       time.Time `json:"createdAt"`
	Id              string    `json:"id"`

	// Payload JSON, shape depends on `type` — `{from, to}` pairs for `status_changed`/`assigned`, `{field, from, to}` for `field_changed`, `null` for `commented`.
	Payload *map[string]interface{} `json:"payload,omitempty"`
	Seq     int64                   `json:"seq"`
	TodoId  string                  `json:"todoId"`

	// Type `created` | `commented` | `status_changed` | `assigned` | `field_changed` — the full read-side vocabulary (DATA_MODEL.md). `created` only ever appears here as a read value, never as something `POST .../events` accepted (I16).
	Type string `json:"type"`
}

// TodoEventList defines model for TodoEventList.
type TodoEventList struct {
	Events []TodoEvent `json:"events"`
}

// TodoList defines model for TodoList.
type TodoList struct {
	Todos []Todo `json:"todos"`
}

// UpdateTodoRequest milestone-4: `title` only — see `updateTodo`'s own description for why `status`/`assigneeId`/`priority`/`dueDate` aren't here. `additionalProperties: false` so a stray `done` is a `validation_error`, not silently dropped.
type UpdateTodoRequest struct {
	// ClientRequestId I19's idempotency key — this endpoint now funnels through the same single write path (I15) as every other mutation.
	ClientRequestId string `json:"clientRequestId"`
	Title           string `json:"title"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoRequest

// CreateTodoEventJSONRequestBody defines body for CreateTodoEvent for application/json ContentType.
type CreateTodoEventJSONRequestBody = CreateTodoEventRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListKeys List the caller's own non-revoked API keys.
	// (GET /keys)
	ListKeys(c *gin.Context)
	// RevokeKey Revoke one of the caller's own API keys.
	// (DELETE /keys/{id})
	RevokeKey(c *gin.Context, id string)
	// GetMe Session-check endpoint backing the SPA's AuthGate-equivalent hook.
	// (GET /me)
	GetMe(c *gin.Context)
	// ListTodos List every todo.
	// (GET /todos)
	ListTodos(c *gin.Context)
	// CreateTodo Create a todo, attributed to the caller.
	// (POST /todos)
	CreateTodo(c *gin.Context)
	// GetTodo Get a todo by id.
	// (GET /todos/{id})
	GetTodo(c *gin.Context, id string)
	// UpdateTodo Rename a todo.
	// (PATCH /todos/{id})
	UpdateTodo(c *gin.Context, id string)
	// ListTodoEvents This todo's own timeline.
	// (GET /todos/{id}/events)
	ListTodoEvents(c *gin.Context, id string)
	// CreateTodoEvent Append an event to this todo's timeline (I15's single write path).
	// (POST /todos/{id}/events)
	CreateTodoEvent(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListKeys operation middleware
func (siw *ServerInterfaceWrapper) ListKeys(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListKeys(c)
}

// RevokeKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeKey(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeKey(c, id)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// ListTodos operation middleware
func (siw *ServerInterfaceWrapper) ListTodos(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTodos(c)
}

// CreateTodo operation middleware
func (siw *ServerInterfaceWrapper) CreateTodo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTodo(c)
}

// GetTodo operation middleware
func (siw *ServerInterfaceWrapper) GetTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTodo(c, id)
}

// UpdateTodo operation middleware
func (siw *ServerInterfaceWrapper) UpdateTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTodo(c, id)
}

// ListTodoEvents operation middleware
func (siw *ServerInterfaceWrapper) ListTodoEvents(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTodoEvents(c, id)
}

// CreateTodoEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateTodoEvent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTodoEvent(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/todos", wrapper.ListTodos)
	router.POST(options.BaseURL+"/todos", wrapper.CreateTodo)
	router.GET(options.BaseURL+"/todos/:id", wrapper.GetTodo)
	router.PATCH(options.BaseURL+"/todos/:id", wrapper.UpdateTodo)
	router.GET(options.BaseURL+"/todos/:id/events", wrapper.ListTodoEvents)
	router.POST(options.BaseURL+"/todos/:id/events", wrapper.CreateTodoEvent)
	router.GET(options.BaseURL+"/keys", wrapper.ListKeys)
	router.DELETE(options.BaseURL+"/keys/:id", wrapper.RevokeKey)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FvdctvGkn6VLuxWiXSBpBQrqRzmSo7lhCf+W1u+OkoJQ6BJTATMIDMD0VwfVe1D7BPuk2z19AAESNCy",
	"Ezunzk1igQCmp6f7669/8CFKdVlphcrZaP4hMmgrrSz6P56I7A3+XqN19FeqlUPl/ymqqpCpcFKr2W9W",
	"K7pm0xxLQf/6T4OraB79x2z36hn/ameXxmgT3d/fx1GGNjWyopdE8+gqRzC8GNxJXQiHFkRzaWJzUSFo",
	"A3eikJlfGUxd4DS6j6OX2j3Ttcq+vpTv1K3SGwUyi0kYQf8ClwsH+F5aZ2FZO5BWnThwOUIqigLNiYXR",
	"4jH83//8L4ilRZViDEo7qNCU0lqp1Xh6rWgj75SoXa6N/G/8CzbzghZX6xjwfSUN8pY2Rqv1xOgCwaIX",
	"DlKtbyV6+a0oEfgsDK6FyQq0FvQKNrlMc0hzTG9hJWSBGYwW346ncAFLzMWd1AbSXKg1wsroElwuLVQi",
	"vRVrPLFAOv356sVzSH66vIJZAncSN3O+6+9vX70EW5uVSBFEsRFbC0LZDRoL56dnMSi8Q+NtJZMGUwcj",
	"AckKXZon/gQgFXQgK10UetO9j45oI7YgYGn0xqIBJe7kmq0r02j9numut68vgpQXtct/Eg4n+Hst70SB",
	"ykGu9S1ICxsyBFcbRZZ7fnoGUjndWTCGtJCo3MTKDPnM7+Nwit7hLir5C27pX5XRFRon2RFTg8JhduEt",
	"YaVNKVw0jzISw8kSozhy2wqjeWSdkWpNpsRnaj/nEelt7uByZXAl3w/8dB9H5J5kOtH8H/R4e3PcEbkr",
	"y6/tsnr5G6aO3s+bfi4ZZfobv8Wt/790WNqHDD1o775dQxgjtgdy+ncOCfKjF/lKZ/ryDpXrQF/fb16p",
	"xgdSfUdWSDa20rVpjrfS1ollgZDQGglhVo0WRskNObQRqZtdvF5MyywZewtLjbZ2spJYZF18G+F0PYVk",
	"qbNtAs0OYKUNJKkuS1QOsySGxOn9n60TrrY37HC0irTejHOhMgak3/SSQci7GGvwxMZQSkILqdb+/qpe",
	"FjKFi9eLYP3JsI6SabNVaSHDQi7RCIfFlhBSV6iAbYaXFAoSVHWZxGA1JNeNrVxHCQiVgVBb0C5HA7Uy",
	"mOq1khYz1iIYFGm+txmSLJO2Ei7N+Q2GbqRzRYJnNAijxdl349afPY5VwuVBIrAVplIQVFj0OtR0yF5o",
	"8tN4zy7pTA4Noz2Vdp1wBRy+d9Mhn2OLCWpceAcspXqOau3yaH428IQ3k8O1/eXmxP36DMlsVd5G+Ec7",
	"h8RJV2AC/4SkMlIb6bb+j6zGp8Jhwjs+WNnpw2X7ltbu2wmzRgf8q8djMpkp/50AnT6f5w+QpIW2mCVg",
	"6zRFzCxoFaySMT+Gxdn34ykIa+VaHS4SrlMYqQnDQ2xOVF0UCTgNteJbeFt0mZwzmjtT49A2/YWH0M7/",
	"enh+H8eVDqSILJOkQ1G87ljWShQW9+N0MnTvHPy9CbmQIEsVW0gyrTCBUSkLtE4rnJzNvpk9PrFgsNR3",
	"hA5kDR4OBCQ7qLlB8vqEncFKCmrFFjKjq4oC+QBuTeGlbnAm4dfGfc8fMZTYB4GkwRD2TorlWwiIAE5n",
	"mqzIOAsJAUlywDsEuS8TLRD21pL3DrlsYybsZA9awYBj9k9lcfa3Ewsyw7LSDlW6hVvcxmy8CEnYQUIb",
	"UgFmUWWVlsoFHRALAFytiIpsjHSBbzRWxqehKz75GKxUKYUUnekb/1I7ZSFvAkm+kZkH4OTlqyt4+e75",
	"c3j3cvFf7y4TEMx1GOahwDssPMixso3egFRpUWeE+zvJtULLmnwAkgJuHGUaDyq7QSF6A2EDOVihN7Qy",
	"ZrIuozjK5TqP4qg2ayLEv36KHxPIeUAV7xvpvzk9fWA3+27uX/Jpfs5E+4DD4PDlVGc4yLdyyYz/4IcS",
	"rRXrT8Am/+rd/Yey7t3PEg5t6QUeCi5SJ++6Uiy1LlD4BIZj8qD0lFI8LHp4Qbg9bhYbko2wY0C6npv3",
	"XfYNrtBQ/kXw52PFiLgGLTWefoqd/gEeHh55MkAXdjB9PgeDVSFIskRvFJpFlnDC6JyRy9rzQa2KbZvt",
	"pClaO7GprshpRz+9ung+LbPxkdD9pz30aG7wFRyXo8on68sHvSk8k+8x88yiZZlekxPMJLNx/u+eqhqp",
	"KbhEcSTVTWX02qC1URzRq73zE0PpGOEAyBz8UlfZ59nKUDrVwE9QSdw17472dwfcNbh+EraT55gzeUY/",
	"6O/aLIbPf5gHX+0xX05K6OE59DIXpmie62+kxSm8QZUhpTGdRBlcbnS9zkHAC2FuM71RE6cnb1CkboIF",
	"0utsQ+a9cxix4WrCaPH9iQ05TQz9g/8jDOBLAMIxTxLbQovsODVkKfuK/vvbVy/jkItmWKFi9hxyMcKP",
	"5MPK6DIGp+8TqIQ0djBDnCUNu6Zj+RD4XOdR/1Avx9id315G+lH17izO4u89pUnlvjvfKUwqh2s0nHdk",
	"+oj+G66+R5hbCvPPrmD0196+6VK7c/qjv8U21VjVRUGpZ8YWeadTsawLYbYwenpxdXHz4tXTS7atHn8q",
	"tsBoXVUojAWfiQqua4qQ0baIbsHqEl3uSdjrV2+vYDqdzpjpJR7wK+fLamffDcP8IICw7ljdcevL8bH8",
	"pWvSH8WJ4XoNS/vJFZsd6jxUtAkvPibSsDS0+c8T5kE5+JVDYrzz+PrHs7xedGsydG9CvvCKCEndLpE0",
	"VY/dK7wbbvJtm5W1Po0LcvA205+1eT4Ig+rEebOcwuemmZ+VRA5lZH8sxQo+2UmnQOkNrGqlsLBtsGir",
	"PFaqdYGcYPkoQR707Zj8jdMfLjWVtfO7+KSE5y9OLehJqVZ6ONI+efbsxDbF+omoXY7KydTnz73aeacu",
	"8BiSaZpLXM0612aHaX4MqVa2LjFjU1xum3I4mFopgirJCa/nWsEqQzV9CpecX4a2Tlc0C5qL9oy9Mfzs",
	"XPWKluh3HWIwaHVxhxmtnVBUMEoUM2eEspU2brZcrRpvaB4tZZYVuBEGYZQsV6vpG1Y7aeMt3xOqDWSq",
	"yy0ItWXclU3pqcJ0DkpDYjGtuUDmcQK5wpkWgliKx3OtoKpNpS3G3gdJG/hepI7tz6CwFJOJYIpKTrei",
	"LBqBcxQZmpYrreUd2vAO4WAlC5zv5OGqLa0fFDprmnXwyFOAR73icbKWarLTBJ2lp8W1y6dwARZTrbIY",
	"pGLiQOvTgtye6Uvb2eJQMQiuo6uN9jLaULRQeB3tqq276g+MnqAwaPpmGoOg5GCyEqlU67Ev4fptP3n2",
	"bGe9gxYeB5LPj7Z9HDLWsS8Du42GTNrfPFBURuvVRK8mkvYr3RZKpFgvbWnJDsjYnalT1uDim9ni7Jtx",
	"zCXlBkhs7o+edssK2+i6yGBZ1OHYlrpWGVEDilng8haOKC0HVCttKG+RbnqtnvZq5UvrT6Htj4WtzwMd",
	"mPngk4AgDhKHura0ZKaEi9LaWqjUd0mNZjTbYSQXwcmi+V23uLUeq/leHO/6e2yxnoYMGW3in519kNl9",
	"0jfdOREbsfHScM9tSW9ztVGkMbGiXbLfK/j56uo1NBbsOwHtBkjf7Q6sE1v48fli4gFoqOvYWAgFJHvr",
	"0+FDI40h6UHdWotiFjKCBJ7S1U2OCr4lbtWJxTA6RMrzQ6Q8sUBIk5BfkdjjOZeodabbM7CwxEJvIBXG",
	"MI4q3AR7mqS6KPjRwOfprEptMITbHz4nrktlHYpsHMNaSMVHnsy4t+qNyJ9eyy0pIFII2Y+UvjNMqe9+",
	"SR6c1sEvKDWG5Onl88ury+7LEyAPM71K8KA5+dK0KNr07MTCdRTeF8rW1xFBruROeaOHORw0DryNt/Qg",
	"9Ly6ganFksXZ92zwtSrkLe6hVAwbZuqKgakpL3vo5a7SNLhBEs5UWqhV0wVZbqFrLE7Y28n5DyAdhelS",
	"EHbZ0KPyRQz/hIBCODRAdxP2nDUkn7lGVG4nDsuKbvK4ePF6EcXRHRrLVOBsejo9JXISlBzNo8fT0+lj",
	"ol3C5Z5xzZp+6hoH+ppv2flDTGErFBaSG1MXaIdt3puUqOTs7oz1MYUfRVHYTqhusHb6Fs2dTHFKZP3i",
	"9eIXrz7ujDcs1xM2vi3mvygj0lnc8puWDvhzbSydwCBElvYGn+uwDol1ejQhlhnR+rR4FPfHXb45Pf1i",
	"QxedpvaRYZd2NoQMU/md3elbzAg9rR9rOT89O7ZMK/esNzLixwnqshRmG/bZH0PZX4oicljuPo52uM62",
	"UaAbSK7forOQhDfcCJdM4ZUPwTbVFQVkf2znp+c8n/OwObzxr2KD2NnDFHqxcS9weehpY9cuygm13TSk",
	"rAdYTQ7lL1LYPvEyrfS0s7tkyFpYvF9we2gu50MlZq+XP3p+9ND5ww+1A0/9A+fFfetarw5PvnPahAlG",
	"lOjQ2Gj+jw+RJOEJJ6I4UqL0FZgs6iYsXMbZWf9+cvMrWVCJn4suB93BHqSUmOy1FekgaYN7byLSfB1t",
	"cg2ihEV8HX2UKQh726Sk/cP+Cd0L/Jq48AKP4QEnQhMZytZfBAFCsjPhuazWS5YivW1GPHiy6dhUUwCG",
	"tpAyeLK9yoW/1Qc30VDlDrUZHQYT6BXQiKUEUnZiGVhsLisodYbFjgV4M1g8JggotFpzia2QaMFp9vFM",
	"l0Iq349F6TP8cPhTeIM8o8XpPwkcNw3nG+F8TQVV5sdValWJtVSimenozL99TmRk4s650W91QOUmW+0Q",
	"lGPR6srr/yuaZVtDGzDOy1ZNXy4qYf+dlR6as0raVgYXm3j0z/lB0RDjezrkjL5tj/lqaUimEJY62xLv",
	"C/GJDu4QfmLI5Mr3CDlR3qWHbHE83fn5TbndpETYRG+kYQpXxyYGKqOz2meLNqzRNEYqTOVK+o6WLyhn",
	"0jqpmkmCzriTdJ1CdC6qCpXlnX90ImEKyV5hKoFS3GJ4sC3KuV2lbSO2A4VraUmYv40PmQC7qHeOlgzs",
	"xkL2qOGunsd3eubXZovMEg+DSZgR83HQdtCHHs2EyWYXb378eXF1+ePVuzeXwXNDQhbWmRRii8bby3jI",
	"PXcCh2iJ1j0JXbEv4pqH00P3/UoiBeb7A2w4+6LYcJTEduZ0AjqcPowOnbnyLwAorCAQAckb5/RSdUhQ",
	"N5S1JPfheMZI1a+q+swCSrHlNs4OzPyc90Mxid1SKKjbYXI/taO0u1kRq0v6tZ3ryM9kM8ZdRzyiWODK",
	"0XsDQHA1aYjOtJb5FSPHMev4MzHjzzHhn9AFg6DUWmZfifL61DrNH6JEOTIE8yxmv3dhnSyKZvyLzCB0",
	"fnzz9tMrPmG2E4yu3a5jPoDGIV8eHXSAO43Q2V4bdBwz/A52Uma+luJybZE3aE86XzbMRJ1J18y0cate",
	"pK4WBSV16AspbTtpTcR+VzbqVkcaVYQyJfMzim1HulAwSnKp3Byu/RDHddTUv9vGVEsRKH7ItdKGhFmE",
	"4FRsw8l8Rl/pSEeJP0fo95X9cYxjyNHP9B1EWo6YAx696zJ+pXBz2Mb8pHDz1wBKmGH5q8PNn83KCV0C",
	"HB1EodmuZT4YjF4VGVoHK2msO0hBVAbaZOjn9QfzEfhYQtIrAhMJldbLGMigkyUWUjF2/cCR1H+o4GF1",
	"hchhq33tcrWa+XE9gqaY0j8kxO2WZ0YHZdFvxx/LeS5ZN1/Z2nbzDINmt9NKo5EYdOdU/jUR7thpfb1I",
	"p499C+NTK7bICk1v+qgzfDPiD1nG8eEQzihx2v+wG8Xxl47M8dOde3g64gvhaxgOEoc9oGkzhNb75KRT",
	"1YfRYSQZzynA7CVngxlVr0t3mFF1Bn1EyG2Gsrn9/K0NOCwkBZQOr9x9K8Ofx/TJRabRf4vYfkUTd3bC",
	"I9/NnHn/E5gpPHp0vM+yV1x99Mg3VD6l8/ID8JlYBxvp8mN9FxjqEh/txXjd1x3fSto+POelpNHxFBa7",
	"nFWrY0HX9zCx4rRGZqF9GTZk5FoqUQQjIPhlbRJP9wMEH88QedTpa6eJvY/X/gW5Yhjo+njC6DX4bxPC",
	"L8jHiSk2tZmQ0O3FhaON1PGU9WHR3DWgXJsimkdN5Izuf73//wAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
