// Package bffapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package bffapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateTodoRequestPriority.
const (
	CreateTodoRequestPriorityHigh   CreateTodoRequestPriority = "high"
	CreateTodoRequestPriorityLow    CreateTodoRequestPriority = "low"
	CreateTodoRequestPriorityMedium CreateTodoRequestPriority = "medium"
	CreateTodoRequestPriorityUrgent CreateTodoRequestPriority = "urgent"
)

// Valid indicates whether the value is a known member of the CreateTodoRequestPriority enum.
func (e CreateTodoRequestPriority) Valid() bool {
	switch e {
	case CreateTodoRequestPriorityHigh:
		return true
	case CreateTodoRequestPriorityLow:
		return true
	case CreateTodoRequestPriorityMedium:
		return true
	case CreateTodoRequestPriorityUrgent:
		return true
	default:
		return false
	}
}

// Defines values for TodoPriority.
const (
	TodoPriorityHigh   TodoPriority = "high"
	TodoPriorityLow    TodoPriority = "low"
	TodoPriorityMedium TodoPriority = "medium"
	TodoPriorityUrgent TodoPriority = "urgent"
)

// Valid indicates whether the value is a known member of the TodoPriority enum.
func (e TodoPriority) Valid() bool {
	switch e {
	case TodoPriorityHigh:
		return true
	case TodoPriorityLow:
		return true
	case TodoPriorityMedium:
		return true
	case TodoPriorityUrgent:
		return true
	default:
		return false
	}
}

// Defines values for TodoStatus.
const (
	Closed     TodoStatus = "closed"
	Done       TodoStatus = "done"
	InProgress TodoStatus = "in_progress"
	Open       TodoStatus = "open"
)

// Valid indicates whether the value is a known member of the TodoStatus enum.
func (e TodoStatus) Valid() bool {
	switch e {
	case Closed:
		return true
	case Done:
		return true
	case InProgress:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// ActivityActor Carried so the UI can mark human vs agent (I20's sibling requirement, not itself an invariant — a rendering fact, not a safety one, `_contract/API.md`).
type ActivityActor struct {
	Handle string `json:"handle"`
	Role   string `json:"role"`
}

// ActivityCursor Round-trips verbatim: the response's `nextCursor` and the request's `cursorCreatedAtMs`/`cursorId` query params name the same two values, mirrors my-task's own `{createdAtMs, id}` cursor object shape adapted to a flat query string.
type ActivityCursor struct {
	CreatedAtMs int64  `json:"createdAtMs"`
	Id          string `json:"id"`
}

// ActivityFeed defines model for ActivityFeed.
type ActivityFeed struct {
	Items []ActivityItem `json:"items"`

	// NextCursor Null when exhausted.
	NextCursor *ActivityCursor `json:"nextCursor,omitempty"`
}

// ActivityItem One `todo_events` row, shaped for the feed — same underlying row `TodoEvent` (this file's own schema) represents on the per-todo timeline, so the two share a rendering component (`_goal/GOAL.md` Done-when 8): same `type`/`payload`/`body` meaning, plus `actor`/`todo` context a single-todo timeline doesn't need to repeat.
type ActivityItem struct {
	// Actor Carried so the UI can mark human vs agent (I20's sibling requirement, not itself an invariant — a rendering fact, not a safety one, `_contract/API.md`).
	Actor ActivityActor `json:"actor"`

	// Body The comment text for `type: commented`, `null` otherwise — same Markdown-to-React-elements rendering rule as `TodoEvent. body` (never raw HTML, I8's mirror).
	Body      *string                 `json:"body,omitempty"`
	CreatedAt time.Time               `json:"createdAt"`
	Id        string                  `json:"id"`
	Payload   *map[string]interface{} `json:"payload,omitempty"`
	Seq       int64                   `json:"seq"`

	// Todo The todo this event belongs to — enough to link/label it, not the full `Todo` shape.
	Todo ActivityTodoRef `json:"todo"`

	// Type Full read-side vocabulary, `created` included (a read value here, never a write one — I16).
	Type string `json:"type"`
}

// ActivityTodoRef The todo this event belongs to — enough to link/label it, not the full `Todo` shape.
type ActivityTodoRef struct {
	Id    string `json:"id"`
	Title string `json:"title"`
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`
	Id        string    `json:"id"`
	Prefix    string    `json:"prefix"`
}

// ApiKeyList defines model for ApiKeyList.
type ApiKeyList struct {
	Keys []ApiKey `json:"keys"`
}

// CreateTodoEventRequest One shape covers all four client-postable `type` values (`_contract/API.md`) — cross-field validation (e.g. `body` required for `commented`, `to` required for `status_changed`) is the handler's job, not this schema's, mirroring the public API's own `CreateTodoEventRequest`. `type` is deliberately an open string, not an `enum`, so `"created"` and any other unrecognised value reach the handler's own dispatch and are rejected there (I16) — the same path, not a special case for one string.
type CreateTodoEventRequest struct {
	// Body commented — the comment text.
	Body            *string `json:"body,omitempty"`
	ClientRequestId string  `json:"clientRequestId"`

	// Field field_changed — which field `to` changes: `title` | `priority` | `dueDate`.
	Field *string `json:"field,omitempty"`

	// To status_changed — the target status (a `Todo.status` enum value; `closed` succeeds on this surface, I18). assigned — the target assignee's user id, or `null` to unassign.
	To   *string `json:"to,omitempty"`
	Type string  `json:"type"`
}

// CreateTodoRequest `additionalProperties: false` so a stray `done` (milestone-1/2/3's removed field) is a `validation_error`, not silently dropped (`_contract/API.md`). No `status` field, deliberately (mirrors the public API's own `CreateTodoRequest`) — every created todo starts `open` regardless of what a caller asks for.
type CreateTodoRequest struct {
	AssigneeId *string `json:"assigneeId,omitempty"`

	// ClientRequestId I19's idempotency key, on the `created` event this endpoint's own side effect writes — required, not optional, since `todo_events.client_request_id` is `NOT NULL UNIQUE` at the schema level for every row including `created` ones.
	ClientRequestId string                     `json:"clientRequestId"`
	DueDate         *time.Time                 `json:"dueDate,omitempty"`
	Priority        *CreateTodoRequestPriority `json:"priority,omitempty"`
	Title           string                     `json:"title"`
}

// CreateTodoRequestPriority defines model for CreateTodoRequest.Priority.
type CreateTodoRequestPriority string

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string  `json:"code"`
		Hint    *string `json:"hint,omitempty"`
		Message string  `json:"message"`
	} `json:"error"`
}

// Me defines model for Me.
type Me struct {
	Active bool   `json:"active"`
	Handle string `json:"handle"`
	Role   string `json:"role"`
}

// Todo defines model for Todo.
type Todo struct {
	// AssigneeId References a user (any role).
	AssigneeId *string   `json:"assigneeId"`
	CreatedAt  time.Time `json:"createdAt"`

	// CreatedBy milestone-4: replaces `ownerId` — attribution only, never access-scoping (GOAL.md).
	CreatedBy string        `json:"createdBy"`
	DueDate   *time.Time    `json:"dueDate"`
	Id        string        `json:"id"`
	Priority  *TodoPriority `json:"priority"`

	// Status milestone-4: replaces `done`. Fixed enum, not an owner-editable table (GOAL.md).
	Status    TodoStatus `json:"status"`
	Title     string     `json:"title"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

// TodoPriority defines model for Todo.Priority.
type TodoPriority string

// TodoStatus milestone-4: replaces `done`. Fixed enum, not an owner-editable table (GOAL.md).
type TodoStatus string

// TodoEvent defines model for TodoEvent.
type TodoEvent struct {
	ActorId string `json:"actorId"`

	// Body The comment text for `type: commented`, `null` otherwise. Rendered client-side through a Markdown-to-React-elements path, never raw HTML (I8's mirror, GOAL.md).
	Body            *string   `json:"body,omitempty"`
	ClientRequestId string    `json:"clientRequestId"`
	CreatedAt       time.Time `json:"createdAt"`
	Id              string    `json:"id"`

	// Payload JSON, shape depends on `type` — `{from, to}` pairs for `status_changed`/`assigned`, `{field, from, to}` for `field_changed`, `null` for `commented`.
	Payload *map[string]interface{} `json:"payload,omitempty"`
	Seq     int64                   `json:"seq"`
	TodoId  string                  `json:"todoId"`

	// Type `created` | `commented` | `status_changed` | `assigned` | `field_changed` — the full read-side vocabulary (DATA_MODEL.md). `created` only ever appears here as a read value, never as something `POST .../events` accepted (I16).
	Type string `json:"type"`
}

// TodoEventList defines model for TodoEventList.
type TodoEventList struct {
	Events []TodoEvent `json:"events"`
}

// TodoList defines model for TodoList.
type TodoList struct {
	Todos []Todo `json:"todos"`
}

// UpdateTodoRequest milestone-4: `title` only — see `updateTodo`'s own description for why `status`/`assigneeId`/`priority`/`dueDate` aren't here. `additionalProperties: false` so a stray `done` is a `validation_error`, not silently dropped.
type UpdateTodoRequest struct {
	// ClientRequestId I19's idempotency key — this endpoint now funnels through the same single write path (I15) as every other mutation.
	ClientRequestId string `json:"clientRequestId"`
	Title           string `json:"title"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListActivityParams defines parameters for ListActivity.
type ListActivityParams struct {
	Limit             *int    `form:"limit,omitempty" json:"limit,omitempty"`
	CursorCreatedAtMs *int64  `form:"cursorCreatedAtMs,omitempty" json:"cursorCreatedAtMs,omitempty"`
	CursorId          *string `form:"cursorId,omitempty" json:"cursorId,omitempty"`
}

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoRequest

// CreateTodoEventJSONRequestBody defines body for CreateTodoEvent for application/json ContentType.
type CreateTodoEventJSONRequestBody = CreateTodoEventRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListActivity The cross-todo activity feed — every event, across every todo, newest first.
	// (GET /activity)
	ListActivity(c *gin.Context, params ListActivityParams)
	// ListKeys List the caller's own non-revoked API keys.
	// (GET /keys)
	ListKeys(c *gin.Context)
	// RevokeKey Revoke one of the caller's own API keys.
	// (DELETE /keys/{id})
	RevokeKey(c *gin.Context, id string)
	// GetMe Session-check endpoint backing the SPA's AuthGate-equivalent hook.
	// (GET /me)
	GetMe(c *gin.Context)
	// ListTodos List every todo.
	// (GET /todos)
	ListTodos(c *gin.Context)
	// CreateTodo Create a todo, attributed to the caller.
	// (POST /todos)
	CreateTodo(c *gin.Context)
	// GetTodo Get a todo by id.
	// (GET /todos/{id})
	GetTodo(c *gin.Context, id string)
	// UpdateTodo Rename a todo.
	// (PATCH /todos/{id})
	UpdateTodo(c *gin.Context, id string)
	// ListTodoEvents This todo's own timeline.
	// (GET /todos/{id}/events)
	ListTodoEvents(c *gin.Context, id string)
	// CreateTodoEvent Append an event to this todo's timeline (I15's single write path).
	// (POST /todos/{id}/events)
	CreateTodoEvent(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListActivity operation middleware
func (siw *ServerInterfaceWrapper) ListActivity(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListActivityParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursorCreatedAtMs" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursorCreatedAtMs", c.Request.URL.Query(), &params.CursorCreatedAtMs, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursorCreatedAtMs: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "cursorId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursorId", c.Request.URL.Query(), &params.CursorId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter cursorId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListActivity(c, params)
}

// ListKeys operation middleware
func (siw *ServerInterfaceWrapper) ListKeys(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListKeys(c)
}

// RevokeKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeKey(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeKey(c, id)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// ListTodos operation middleware
func (siw *ServerInterfaceWrapper) ListTodos(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTodos(c)
}

// CreateTodo operation middleware
func (siw *ServerInterfaceWrapper) CreateTodo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTodo(c)
}

// GetTodo operation middleware
func (siw *ServerInterfaceWrapper) GetTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTodo(c, id)
}

// UpdateTodo operation middleware
func (siw *ServerInterfaceWrapper) UpdateTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTodo(c, id)
}

// ListTodoEvents operation middleware
func (siw *ServerInterfaceWrapper) ListTodoEvents(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTodoEvents(c, id)
}

// CreateTodoEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateTodoEvent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTodoEvent(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/todos", wrapper.ListTodos)
	router.POST(options.BaseURL+"/todos", wrapper.CreateTodo)
	router.GET(options.BaseURL+"/todos/:id", wrapper.GetTodo)
	router.PATCH(options.BaseURL+"/todos/:id", wrapper.UpdateTodo)
	router.GET(options.BaseURL+"/todos/:id/events", wrapper.ListTodoEvents)
	router.POST(options.BaseURL+"/todos/:id/events", wrapper.CreateTodoEvent)
	router.GET(options.BaseURL+"/activity", wrapper.ListActivity)
	router.GET(options.BaseURL+"/keys", wrapper.ListKeys)
	router.DELETE(options.BaseURL+"/keys/:id", wrapper.RevokeKey)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FzrctvGkn6VLuxWicqCpJQ4p3KYX4rjJDzHt2PLv45SwhBoEhMBM8jMQDTXR1v7EPuE+yRb3TO4kaAk",
	"J3ZS+8clksBcerq//voy/hCluqy0QuVstPgQGbSVVhb5w3cie4O/1mgdfUq1cqj4T1FVhUyFk1rNf7Fa",
	"0Xc2zbEU9Ne/G1xHi+jf5t3Qc/+rnT8zRpvo7u4ujjK0qZEVDRItosscwfjJ4FbqQji0IJqvpjYXFYI2",
	"cCsKmfHMYOoCZ9FdHL3U7gddq+zzr/KdulF6q0BmMS1G0F/gcuEA30vrLKxqB9KqEwcuR0hFUaA5sTBZ",
	"fgX/+9//A2JlUaUYg9IOKjSltFZqdTq7UrSRd0rULtdG/if+AZt5QZOrTQz4vpIG/Za2RqvN1OgCwSIv",
	"DlKtbyTy+q0oEfxZGNwIkxVoLeg1bHOZ5pDmmN7AWsgCM5gsvz6dwQWsMBe3UhtIc6E2CGujS3C5tFCJ",
	"9EZs8MQCyfSnyxfPIfnx2SXME7iVuF34p/729tVLsLVZixRBFFuxsyCU3aKx8OTsPAaFt2hYVzJpMHUw",
	"EZCs0aV5wicAqaADWeui0Nv+c3REW7EDASujtxYNKHErN167Mo2W90xPvX19EVZ5Ubv8R+Fwir/W8lYU",
	"qBzkWt+AtLAlRXC1UaS5T87OQSqnexPGkBYSlZtamaE/87s4nCIb3EXq5K10u4vUaUNfDA/sqTBGYgZW",
	"86LeLWlnUApzA3ldCgW3FsSGVjRZfnl2YsHKVSHVhq1IGixROa960lks1qy/6lYYKZTz+gkGVYaGXlqL",
	"NDwtwIo1uh1ohTEk16SWRqRufvF6OSuzhLcSR5XRFRonPXjkQmUF0l9uV2G0iKyjYUnNSbtGfqBf/EKz",
	"aPHPZoDw+M9x87he/YKpo3EacT2tjR2T1xsChakzsrJwi2YlnCwXLLoG5k4sJArfOz9CAkJl4XeGHfo5",
	"5Z+eGhQOswv3wibz8N0yS+DXGs0OKmFEaUGRddDrbCZuqwmtarQxlJKM0EK5mzphb4IuJR/SbtgYZHaX",
	"gB8a/CaDqYlMVA4zYGVaF8KFab3gxoTfG5c+rrUphYsWkVTuL0+iVpRSOdygIVnK7OET6Y/Kb9x3KD+g",
	"x7DhwqTDcvjHfdDVjLV0WNLYYTJhjNjR5+7oGCKL4tU6WvzzcWOG9+5+3ofFl3VRwDZHBfg+F7V1mM2i",
	"OFJ1UYgVKa4zNe6Lxm/nPnnwHg5U9JVCSJzO9DXe0jITMHob+3PPYK0N69MaMevwtyYLLXZs2HoLyaXO",
	"9DN6O4EJI+ZaFg2o+l2fgsHKoKUZQCses0IzpYnByRILSZYdcIUU1+bC4AAOWlHCJLneaFHMf3x18ZzM",
	"H77XCqcssW9OF36NCckhmSeV2BVaZMk8Welsl0CJQrHPqYraQiII6JI5SyABdnfvGW+k2hQ4XB8jMgG5",
	"Qm8LBisUbkz9RYOfj1EED7Z3cUQrPDwhIiapLgk7gVdHh8LbWzTfY5bEkJCCJKBdjmYrbc9fvhDmJtNb",
	"NXV6+gZF6qZYMBbbnniJzICwvdOcgRfZxPs3I7bsImNYfnNiA6IE5B3qZnyIuK3lDtAgIz9G4o1GXhkF",
	"hDgKB8pSzjJJQhLF6570/QqOrKgzC4u/PhKZSAkee5YkvDe47rBi/zR/IOM2KDL2wXCrU7GqC2F2MSRB",
	"SAlIlRZ1RhRG8LMexiFHgx3b2BrpkDwiH/Ty/C+ns0Mx7qNEFvmdhwfjoKn9Awobvg9Kml2O6qq3GYIB",
	"RhRYYaHVxpLB0EJR6XqT06dCqpt5IVZYgAyOnrGGJMRamHgYmh2Y1xHVcNI9xq+zEPyzo5us5N9xd+g5",
	"foMKe15rP4XWG1zL94/cW3h4eKjdWo5v+rn0kdZw4ze4+wiP6aV34Cv31sljji3E85wWg3rh36Hf8uQk",
	"1bfExIlnr3VtGopbaesIAIInCEyIfMcBe2S9TI22drqWWGT9GG+Cs80MgvNoduAheAC+Tu//bJ1wtb32",
	"QQfNIi3rt6eVFJT9oleN2ksbPOVJS9YIlNlP1qtCpnDxetmwtnEZJbNmq9JChoVcoREOix2xbF2hCnQt",
	"UGoFCaq6TNjrJleNrlxFnoQKtfOuBGplMNUbJS02QGRQpPneZmhlmbSVcGnuRzD0IJ0rMqc1CBNCqTam",
	"Yd9UCZe3JL/CVAoKlyyyDAncjnPMcXfZnko7T995zsZszmtMEOOSDbCU6jmqjcujxfnIG6wmh3Pz182J",
	"8/w+LPVaxTrif7QLSBiBEvgXJJWR2ki34w9Zjd8Lh4nf8SHG6cNph5rW7tsJs0EH/leOSUllZv5zAnT6",
	"/jy/hSQttCXPY+s0RcwCSSOt9HFvDMvzb05nIKyVG3U4SfieWF9NcWzITwRO4jTUyj/ySL7QOM/70S74",
	"sP3zux9XepAyTiDWorC4T8qTsWcXwM8mZEKCNFXsIMm0wgQmpSzQOiKm5/Mv51+dENcq9S2hA2kDw4GA",
	"pIOaaySrT7wxWEmBfbGDzOiKmPgYbs3gpW5wJvHDxkPLnzRx30NA0mCIt05iGDsIiOAdunXCOAsJAUly",
	"kHsRZL4+2QTC3liy3lFeHNTEG9nDrPHQMIensjz/64kFmWFZaYcq3cEN7uImwugIlWcinpSorNJSuSY+",
	"IRaG6zUFu8yofM6l0TJ/GrryJx9TXJAOA6aZX+R1iNivZcYAnLx8dQkv3z1/Du9eLv/x7lkCwtMbD/NQ",
	"4C0WDHJe2BRIedpHuN+tXCu0XpIPQFLAjaNM40FhNyhEIxA2kIEVekszYybrMoqjXG7yKI5qs0HFPOJh",
	"O24oWSneN6v/8uzsgd3smzkP8jg798nGAw6D41+nOhvPEOXSZz0PfijRWrF5BDbx0N3zh2vde96vcGxL",
	"L/Bw4YKYeH8VK60LFJzE/cSJr7iZbGxtlyE2us/M93JiuEaDKuXsOvuKCXENmup09plCyfDKdyN0oYPp",
	"JwsK6AtBK0v0ViHn1zgp6ZyRq5r5oFbFro3B0hStndpUV2S0k5CPOD3iun+3hR6NDT6D4Xqv8mh5sdOb",
	"wQ/yPWbMLFqWyZKcYiY9G/f/7omqWTU5lyiOpLqujN4YtDaKIxqajZ8YSk8JH4774qiuso/TleOhYiuS",
	"uK/ePel3B9xXuGEQ1q3nmDExox+1d22W4+f/adNGM3jDOSHM+sUCcLnhuF3cl00KZH6QLoJJL10Uw/Dg",
	"fwsD+PNzS0NB/+3tq5chYQoZVqg8ew6xGOFH8mFtdBmD03cJVEIaOxohzpOGXdOxfAh8rvcqvzSIMbrz",
	"24tI7xXvb02CHZH/eKKrozD/6i+MPu3tm75qd04fhltsQ431sdQZTL6/uLy4fvHq+2detwb8qdiBR+uq",
	"QmEsZ9FA+Npuk1prEd2C1SW6nEnY61dvL2E2m82b1DgBPhdCOJAdhflRAPGyazJvjS3Hx+KXvkrfixPj",
	"+Rq/2kdnbDrUeShpEwY+tqTx1dDmP24xD67DDzm2jHeMr789yht4tyZCZxXiZDoiJHU7RdJkPboh2Ay3",
	"+a6NylqbxiUZeBvpz9s4H4RBdeJYLWfwsWHmRwWRo4W63xRiBZvshVOg9BbWtVJY2NZZtFkeX04JKWvy",
	"EmRBX5+Svfnwx6eaytrxLh4V8PzBoQW9KdVaj3va73744cQ2DQtTUbsclZMpx8+D/oFeXuArSGZpLnE9",
	"7303PwzzY0i1snWJmVfF1a5pCQBTK0VQJX3Ay1wraGXoKJjBMx9fhtaW/tIsaF9K8Ngbw0/OVa9oimHn",
	"RQwGrS5uMaO5E/IKRoli7oxQttLGzVfrdWMNzaulzLICt8IgTJLVej1748VO0njrnwnZBlLV1Q6E2nnc",
	"lU3qqcJ0AUpDYjGtfYKMcQJ9hjMtBLEUxnOtoKpNpS3GbdES34vUef0zKCz5ZCKYopKznSiLZsE5igxN",
	"y5U28hZtGEM4LmUuuvX4rC3NHwQ6byr58AVTgC8GyeNkI9W0kwSdJdPi2uUzuACLqVZZDFJ54kDz04S+",
	"RWW42t4Wx5JBcBVdbjWv0YakhcKrqMu2dtkfmHyHwqAZqmnsOzema5FKtTkNnQjSkmp32juq4XEg+f7V",
	"tpeFlPWU08BuqyGT9hcGispovZ7q9VTSfqXbQYnk66UtLekBKbszdeoluPxyvjz/8jT2KeUGSLg6nPFu",
	"vcC2ui4yWBV1OLaVrlVG1IB8Fri8hSMKywHVWhuKW6SbXanvB7nyleVTaHuEwtYXgQ7M2fkkIIiDxCGv",
	"LS2pKeGitLYWKuVOMaM9mnUY6ZPgpNF+rBvcWcZq/yyedjVbr7FMQ8aUNuF35x98y0ZfdRdEbMSWV+P7",
	"jlY0mquNIomJNe3S272Cny4vX7e9KFwJaDdA8m53YJ3YwdPnyykD0FjnVaMh5JDsDYfDh0oaQzKAumNV",
	"/K+JW/V8MUwOkfLJIVKeWCCkSciuaNmnvteG85fNGViuR24hFcZ4HFW4Dfo0TXVR+FcDn6ezKrXB4G6/",
	"/Ri/LpV1KLLTGDZCKn/kydz3l7ES8em13JIcIndM7XlK7o6j0Hc/JQ9O62AXFBpD8v2z588un/UHT4As",
	"zAwywaPqxKlpUbTh2YmFqyiMF9LWVxFBrvTdgo0cFnBQOGAdb+lBqHn1HVOLJcvzb7zC16qQN7iHUjFs",
	"PVNXoaUspJcZen1VaRbMIAlnKi3UqqmCrHbQVxYn7M30ybcgHbnpUhB22VCj4iQGvyGgEA4N0NOEPecN",
	"yfdcIyp3U4dlRQ8xLl68XkZxdIvGeipwPjubnRE5CUKOFtFXs7PZV0S7hMuZcc1FqKLThw2O1DaTUc1m",
	"xRGVJGfbjpGQuTctW2TUw14ewVXNwLHoFwp0tsQD1tJYFwNBsm9mSQKwTXivHv+T2qKh7zhkCcW+udFF",
	"16sTTuVIH+DpDF6xa2hYQculDxvSkmZPs0Jal8Ak+a/5Rjo7D4/MrUnnFs0tGhaD0bVDY+fQvucsOdim",
	"Wc1D+JvXT2nsD4UspYuDqBZw0Ph2RwZb1U3Hm9MDWzuxUBVCqilzOW5+m3pGSe6KhC21WkDCsyQwyXAt",
	"6sLBV2exh3Ox33oXnvgWzqfnZ2c+9W/lLZ6GxqR7u/7iALplbRnebV1VheRz3CAzaW080XBcF58IKLTy",
	"zSJ67Q1NSOOjh1IUFP9jFoQTj8QTZPH9NsXAN1vug2mu0fZYl694KlFyyf3+FsZQrdmKHUjVtcGE5+Tw",
	"CV27Ux8HecrOmmfaPkuQru209N2vHuLfO6h8p++gc7G/qwX4TEqJQtmu9W6grcmlsDf/oBHeormVKbKu",
	"Nm0xrXPOhX2hDSahH3nCvcBBO+A/4Jyb7CxhN+B7ZwRXf0J/XJificUJnU+7+IBFFL3x2VC0Fj3vzc8o",
	"Y0SJZBfchygJTnjHURzRaUSLiFcRxb3m7VK8l2VdRovzED6FT4d5oLt4fMyDAx6M/2B66f5hfeqkHW0/",
	"oPs5Hl4a+PLs7JO1rg96SUc62C/4YBqb8i0kTDfWyLXDHtbyRYEnfm1jU7Z7mPduPfAr5w+/Mujb557u",
	"uiyF2TV54G5hDVh2LZ3eObDHiB9yGDMefN50BI16r7eevgZkCA3EFpJrUxdo5/f7tttz79Fn8FQUhe0F",
	"m020MGssjzX/9fLvTAB8f3uTp+GUg38s4G+JLtdZ3EbobUDLzKThanSQITZqH2DXd8zyaPLoc+pf15Z1",
	"5MpKe8ODgEfxzm71DWbE/+3sUygQzT68TLI/FcWUYbpGO5h+et0o0I2kh9+is5CEEa6FS1qmkOqKbIeP",
	"7cnZE3/L5mF1eMNDeYXo9GEGg+huL/RiktNGX12cJtRu26QVBpS7yQL2u5wTqdZ61ttdMqYtfnl/x92h",
	"ujwZK5KyXH7r+dFLTx5+qb22NDxwP3mfLAxOvnfa4/6GmG6H4ZwB71JuvhBxD5qTBpX4sehy0N8ygJQS",
	"k73GGDpI2uDeSGtt4Cra5hpECcv4Kro31hX2pkmqDg/7R3Qv8HPiwgs8hgc+lTeVofD6SRAgpOumns20",
	"VrIS6U3TpOjvJx27mxSAoS0FjJ7sIPfOj4K/AhCSPb3gfHLoTGBQAqI4O6QVTqwHFpvLCkqdYdHFsb5z",
	"+iuCgEKrjS8SFRJty/8zXQoipVoBSmbW4fBn8Ab9Tau+rwzU9Vo4rgqgyrjhslaV2EglXP8Wxcd7Rh+h",
	"+ezeL3VA5Tay6kLsY97qkuX/GdWyrQKNKOezVkyfzivhcMxKj3UKJ20x3pdL/AW+EL54Hz+Qoc9Jtw0e",
	"vVgyR74RAZPlefBPzaWJ/dRFJtfc5eJTvV2C02ucv6P58W0lXa9f2MSgKW8Gl8d63iqjs5rznTbM0ZT2",
	"K0zlWnJPBpdEM2mdVE0vXK9hV7peKTUXVYXK+p3f21M3g2SvtJJAKW4wvNiWlVxXK6Io77D0Ki0t5q+n",
	"h0zAmygbR0sGusbGPWrYVaT8k8z82nynZ4mHziR0ObMftD30oVczYbL5xZunPy0vnz29fPfmWbDckFIM",
	"80wLsUPD+jIaxnULDt4Srfsu9HV8EtM87H+9G9bC+FLZATacf1JsOEpie52mf1ac5AUEIiB5Y5w+OdaR",
	"oL4ra0nuw/7MI9WwLuiTaqXY+UaEDsz4tvZDPsmbpVBQt1fCue9UaXe9JlaXDKsTVxHfrPYYdxX5JvsC",
	"147GDQDh6yFjdKbVzM/oOY5px+/xGb+PCf+ILigErHYgs89EeTk5nOYPUaIcPQT73Nqw+m6dLIqmgZnU",
	"IPQucPvR42sW4XYCcG61LeOPoHGIlycHPUy9Vp75XiPPaezhd7QXYM7VAJdri36D9qT3/xPMRZ1J179G",
	"bsl8alFQUIdcCmgbIjZE7LvCRz+/34giFNo8PyPfdqSPAiZJLpVbwBW3IV5FTQW3ba1oKQL5D7lR2tBi",
	"lsE5FbtwMh/RGXGkJ8L/pwLDzig+jtMYcuSu9ANP6z3miEV3fTKfyd0cNuI8yt38MYASujD/aHfze6Ny",
	"vt0vmlUPvdC8a/oadUaviqxN4h2EICoDbcI14NF4BO4LSAZlTCKh0vIaAxlsb08Tdn07lidlvBqvbsUU",
	"/iEhbj89Mzko7H19el/M88zL5jNrW9eRN6p2nVS6++66dyp/joc7dlqfz9PpY7c5ObTyGlmhGfTP9tpH",
	"J/4q5ml82EY6SZzmH7pmUv7qyE00enIPTyf+i3Cf0zuJw2LsrGmjHlya7NWlYTJSQVuQg9kLzkYjqkGf",
	"yWFE1WtVFSG2GYvm9uO31uH4RZJD6fHK7ranv+A5JBfN/3vQ3gMdu6s+dolzBl98cbxTYC+5+sUX3BLw",
	"mN6Bb8GfiXWwlS4/1jkAY31OR7sJWPZ1z7aStpPMx6Uk0dMZLLuYVatjTpe7cPi/hyB8y0IDTtiQkRup",
	"RBGUgODXS5N4OrfA3R8h+mbdzx0mDq5f/wmxYmhJvj9gZAn+v3HhF2TjGVd9fW4mBHR7fuFoK9DpzMvD",
	"N0F4UK5NES2ixnNGdz/f/V8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
