// Package bffapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package bffapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`
	Id        string    `json:"id"`
	Prefix    string    `json:"prefix"`
}

// ApiKeyList defines model for ApiKeyList.
type ApiKeyList struct {
	Keys []ApiKey `json:"keys"`
}

// CreateTodoRequest defines model for CreateTodoRequest.
type CreateTodoRequest struct {
	Title string `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string  `json:"code"`
		Hint    *string `json:"hint,omitempty"`
		Message string  `json:"message"`
	} `json:"error"`
}

// Me defines model for Me.
type Me struct {
	Active bool   `json:"active"`
	Handle string `json:"handle"`
	Role   string `json:"role"`
}

// Todo defines model for Todo.
type Todo struct {
	CreatedAt time.Time `json:"createdAt"`
	Done      bool      `json:"done"`
	Id        string    `json:"id"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// TodoList defines model for TodoList.
type TodoList struct {
	Todos []Todo `json:"todos"`
}

// UpdateTodoRequest defines model for UpdateTodoRequest.
type UpdateTodoRequest struct {
	Done  *bool   `json:"done,omitempty"`
	Title *string `json:"title,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListKeys List the caller's own non-revoked API keys.
	// (GET /keys)
	ListKeys(c *gin.Context)
	// RevokeKey Revoke one of the caller's own API keys.
	// (DELETE /keys/{id})
	RevokeKey(c *gin.Context, id string)
	// GetMe Session-check endpoint backing the SPA's AuthGate-equivalent hook.
	// (GET /me)
	GetMe(c *gin.Context)
	// ListTodos List the caller's own todos.
	// (GET /todos)
	ListTodos(c *gin.Context)
	// CreateTodo Create a todo owned by the caller.
	// (POST /todos)
	CreateTodo(c *gin.Context)
	// DeleteTodo Delete one of the caller's own todos.
	// (DELETE /todos/{id})
	DeleteTodo(c *gin.Context, id string)
	// GetTodo Get one of the caller's own todos.
	// (GET /todos/{id})
	GetTodo(c *gin.Context, id string)
	// UpdateTodo Update one of the caller's own todos.
	// (PATCH /todos/{id})
	UpdateTodo(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListKeys operation middleware
func (siw *ServerInterfaceWrapper) ListKeys(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListKeys(c)
}

// RevokeKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeKey(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeKey(c, id)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// ListTodos operation middleware
func (siw *ServerInterfaceWrapper) ListTodos(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTodos(c)
}

// CreateTodo operation middleware
func (siw *ServerInterfaceWrapper) CreateTodo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTodo(c)
}

// DeleteTodo operation middleware
func (siw *ServerInterfaceWrapper) DeleteTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTodo(c, id)
}

// GetTodo operation middleware
func (siw *ServerInterfaceWrapper) GetTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTodo(c, id)
}

// UpdateTodo operation middleware
func (siw *ServerInterfaceWrapper) UpdateTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTodo(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/todos", wrapper.ListTodos)
	router.POST(options.BaseURL+"/todos", wrapper.CreateTodo)
	router.DELETE(options.BaseURL+"/todos/:id", wrapper.DeleteTodo)
	router.GET(options.BaseURL+"/todos/:id", wrapper.GetTodo)
	router.PATCH(options.BaseURL+"/todos/:id", wrapper.UpdateTodo)
	router.GET(options.BaseURL+"/keys", wrapper.ListKeys)
	router.DELETE(options.BaseURL+"/keys/:id", wrapper.RevokeKey)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFldcts4Er5KF3erLE1RP048L3pTEsfRTjJx2crTOGVCRFNETAIcAJTCTalqD7En3JNsNUBRlEVFyayT",
	"fbJEgehu9Ndffw1/CWKVF0qitCaYfAk0mkJJg+7LC8Zv8M8SjaVvsZIWpfvIiiITMbNCydEnoyQ9M3GK",
	"OaNPf9eYBJPgb6Pd1iP/qxldaq10sNlswoCjibUoaJNgEsxTBO2NwUqojFk0wLaPBiZlBYLSsGKZ4M4y",
	"6DLDYbAJg9+Vfa1KyX+8lx/kg1RrCYKH5AyjT2BTZgE/C2MNLEoLwsgzCzZFiFmWoT4z0Js9h//869/A",
	"FgZljCFIZaFAnQtjhJL94Z2kQD5IVtpUafFP/AnBvCPjchkCfi6ERh/SWiu5HGiVIRh0zkGs1INA579h",
	"OYLPhcYl0zxDY0AlsE5FnEKcYvwACRMZcujNfu0PYQoLTNlKKA1xyuQSIdEqB5sKAwWLH9gSzwzQmb6Z",
	"v3sL0dXlHEYRrASuJ37VP27f/w6m1AmLEVi2ZpUBJs0atYGL8XkIEleoHVa40Bhb6DGIErRxGrkMQMwo",
	"IYnKMrVur6MUrVkFDBZarQ1qkGwllh5dXKFxMdOq2+tp7eW0tOkVszjAP0uxYhlKC6lSDyAMrAkIttSS",
	"kHsxPgchrWoZDCHOBEo7MIKjz/kmrLPoCm5aiN+wok+FVgVqK3whxhqZRT51SEiUzpkNJgEnN6zIMQgD",
	"WxUYTAJjtZBLgpLPqfmeV4TD3MHjQmMiPnf8tAkDKk+CTjD5g15vFoctl9u+fGzMqsUnjC3t74N+KzzL",
	"7Af+gJX7Kyzm5hTQ69PbNDaY1qw68NPt2eXIS+fyXHHVYr19f6ywGdKHnH1+i3Jp02DybDwOg1zI7ffz",
	"8MRB+U26PPClemAVux/HimNnxlLhOePghxyNYUs8nUu39W79oa+P1nsPu0J6h4eOs9iKVduLhVIZMkeB",
	"KZM86w6LSOm06/UG9fJwa6zLN0r1kxQbV/JIOEdqqsHRwS9lwb/PelcV+u1rv/Zrcbf/sRPprkSruPr2",
	"UnQne6oQ/ZZdbnxwTn61Eo8f+V+u0ccQp/TJxCHkUKu8eP36zGxb5IDaNkpLDRr5fsfq5SJDY5XEwXOI",
	"hnEqMBm1no3uqctrFtvR9Ho2zHnUDyFW0pQ5clAyq2BRbZsQ6FJKIZcgpHuk1tLpC+pMdQ8bwuUKddWI",
	"qbZrBpRvlUYsJTX8N9YW78nEfq8PQaNR2Qo52Y6EtKgly0ZWM2kKpe1okSRRbXf7ai44z3DNNEIvWiTJ",
	"8Mbnmk7j1q+J+q6jkvhZVMBkZdMmGGHAFBhPQCqIDMalFraKwCEKqbtyjDOmkUOKGkFJKEpdKIMhJEq7",
	"08DPLLZeo2hkRkmIVIGSFWJYsTzbOpwi46ghVnlO3XspVmjqPZiFRGQ42flzZuCTWpD9+kBHW4kMvzgh",
	"9EtbkvaipZCD3UlQLilaSgJpIYOxkjwEITkWKDnZJ4NeFO172woRetEBSuAumK+V89F4I0riXdBvNEtR",
	"LjIRw/R6Br0XyDTqfZiGwJYkRhIWC7nsA5Pch/3i9esdejsRHnrg1a826onA2gcCgF0r4MJ8UkJaKLRS",
	"yUAlA0HxCltBjqQFhckN4YDAbnUZ+xOcPRvNzp/1Q+cPIVUuM6c5KfUUrT+wtSozDousrNO2oAGA6Qpw",
	"hQQnVS5Tr8EVR0CZKB2jAWGHd/IVZmKBmlnMKi/JbUuV1qFPILp+fzuHkaOpCBiJtpC21A6OUsEDViCM",
	"KZmM3WyilfUwQMkLF7pb3CNE+71Ie0SULb8W+ztV7RFLx9kJ2si9O/oi+Cbah+6EFCZbO2+80l3QbqRD",
	"6cRYQlH6uieRPb+GLYJDMGoXAJ13E4GxrIKXb2cDR0BdWn+LEGGAmQfyuwOkIUR7VLdULBtdvZ++dQh+",
	"RU/XKUr41anhhruDvBpYzAuaAh0cp9ezIAxWqI1n4PPheDgmsq+PKpgEz4fj4XNSoMymrkOMtuJxifaQ",
	"w2/9mdel7EcaZiC6p6nSHJLymalnE1aI0ercZ3IIL1mWmRZDbiE+vEW9EjEOqZtOr2e/0XLwY0BWtWYp",
	"vyz033K0qeJh01YaFnblBkIai4xTDuqCbhaw2Crtz5C6pEvijAeTgOyTcRJE7dn+2Xj8ZBNmS8Efmeyb",
	"QZigLF1kK/WAnEBr3Ax/MT4/Zqbxe7Q3H7vZqcxzpqs6zv2Z+7EpIsLa3CYMduXksZGhxQ6UoDUQ1Tvc",
	"MxsN4b1jPhOrgnjQpe1ifOEvI07D4cZt5QGxw8MQ9ijpEV+4ymwoY0cuTFbrbS9sM5dHF6J/SGx55nxK",
	"1LAVXdSFFu8eTVEHcLk4PB2/mv/V/NFLF6dfam539hPujVPTo3o4yHwr28QJmuVoUZtg8seXQJDzxBNB",
	"GEiWE+E42bwTp1aXGLbQ/1gsfiQE5fi97LLflh9TSo5RCLwNBEokBfhoJ9Iqd8E6VcBymIV3wVcJmhnK",
	"UUeyr9C+wx/JC+/wGB94/TkQ0jPbkzBArTEH/hKqqZIFi1132l3jHLvCqYmhmXQ6M3uD/oLH9UXacyt/",
	"21LcbRFCPXfdMwu0CUrurttKWbClkG5UeHSpRpXuvko1qBe5m85GG3xPi/LC5VhTmLswf2D2m1nyW3qC",
	"8/UHNoLd/oUyHWmNXPruBY+coPG3jNbdSdcddi/Pfozx945xjAWlslaQCAvFK+jNzuvuQNkKgYskQU1Q",
	"I893Crg/hIhm2Ygkl7YGEpaZjk7CVc6EdDltmsnuwuqRtHC4bMkLpxwakedVxiEZ+ZsT7Q7OkJqrcUav",
	"cqb5aHrz8s1sfvly/uHmsgac1+WD2s4gYxVqF3G/C3c7h2u2RWNfKF49GeYOr/A2+7cOROybA9CfPyno",
	"jwLe04HDYg318Wmot/4J8wTV4Q8ImHPCYZlvrxd8vbRJ8KQ8+qoWekUvOc6SwDKNjFcDvxEHwX2ZGQWR",
	"VPY+oQYfQU8yW2qWZRUIjnmhKCH1xgftsxNhzugOYacUjF/+f1Iw3vhRBbOjrM5G1D576M2e9yfApKLx",
	"tGlFh/+l8pTl/ldFGVsom9aj4l4eduwWJUovBOfYrRev0Haf9finVFSrkn5y7q7QfkPinl53uvk2Tr+r",
	"FKl0ri7nw4Ps7a5ZfxAdH97jfhMd/xzw1DfhP5uO/zfc+RM9CT33EurVFnmlzoJJ4IThIkmCzcfNfwMA",
	"AP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
