// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateTodoRequestPriority.
const (
	CreateTodoRequestPriorityHigh   CreateTodoRequestPriority = "high"
	CreateTodoRequestPriorityLow    CreateTodoRequestPriority = "low"
	CreateTodoRequestPriorityMedium CreateTodoRequestPriority = "medium"
	CreateTodoRequestPriorityUrgent CreateTodoRequestPriority = "urgent"
)

// Valid indicates whether the value is a known member of the CreateTodoRequestPriority enum.
func (e CreateTodoRequestPriority) Valid() bool {
	switch e {
	case CreateTodoRequestPriorityHigh:
		return true
	case CreateTodoRequestPriorityLow:
		return true
	case CreateTodoRequestPriorityMedium:
		return true
	case CreateTodoRequestPriorityUrgent:
		return true
	default:
		return false
	}
}

// Defines values for TodoPriority.
const (
	TodoPriorityHigh   TodoPriority = "high"
	TodoPriorityLow    TodoPriority = "low"
	TodoPriorityMedium TodoPriority = "medium"
	TodoPriorityUrgent TodoPriority = "urgent"
)

// Valid indicates whether the value is a known member of the TodoPriority enum.
func (e TodoPriority) Valid() bool {
	switch e {
	case TodoPriorityHigh:
		return true
	case TodoPriorityLow:
		return true
	case TodoPriorityMedium:
		return true
	case TodoPriorityUrgent:
		return true
	default:
		return false
	}
}

// Defines values for TodoStatus.
const (
	Closed     TodoStatus = "closed"
	Done       TodoStatus = "done"
	InProgress TodoStatus = "in_progress"
	Open       TodoStatus = "open"
)

// Valid indicates whether the value is a known member of the TodoStatus enum.
func (e TodoStatus) Valid() bool {
	switch e {
	case Closed:
		return true
	case Done:
		return true
	case InProgress:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`
	Id        string    `json:"id"`
	Prefix    string    `json:"prefix"`
}

// ApiKeyList defines model for ApiKeyList.
type ApiKeyList struct {
	Keys []ApiKey `json:"keys"`
}

// CreateTodoEventRequest One shape covers all four client-postable `type` values (`_contract/API.md`) — cross-field validation (e.g. `body` required for `commented`, `to` required for `status_changed`) is the handler's job, not this schema's, the same way my-task's own `buildAppendInput` does it in code rather than a `oneOf` discriminator. `type` is deliberately an open string, not an `enum`, so `"created"` and any other unrecognised value reach the handler's own dispatch and are rejected there (I16) — the same path, not a special case for one string.
type CreateTodoEventRequest struct {
	// Body commented — the comment text.
	Body            *string `json:"body,omitempty"`
	ClientRequestId string  `json:"clientRequestId"`

	// Field field_changed — which field `to` changes: `title` | `priority` | `dueDate`.
	Field *string `json:"field,omitempty"`

	// To status_changed — the target status (a `Todo.status` enum value). assigned — the target assignee's user id, or `null` to unassign.
	To   *string `json:"to,omitempty"`
	Type string  `json:"type"`
}

// CreateTodoRequest `additionalProperties: false` so a stray `done` (milestone-1/2/3's removed field) is a `validation_error`, not silently dropped (`_contract/API.md`). No `status` field, deliberately (Clara's decision, not a residual gap): every created todo starts `open` regardless of what a caller might ask for. มายด์'s own walkthrough only requires *changing* a todo's status after it exists, never setting one at creation, so `open` as the universal starting point already satisfies the brief. The asymmetry with `assigneeId`/`priority`/`dueDate` being settable here is intentional — `_contract/API.md` states the same reasoning.
type CreateTodoRequest struct {
	AssigneeId *string `json:"assigneeId,omitempty"`

	// ClientRequestId I19's idempotency key, on the `created` event this endpoint's own side effect writes — required, not optional, since `todo_events.client_request_id` is `NOT NULL UNIQUE` at the schema level for every row including `created` ones.
	ClientRequestId string                     `json:"clientRequestId"`
	DueDate         *time.Time                 `json:"dueDate,omitempty"`
	Priority        *CreateTodoRequestPriority `json:"priority,omitempty"`
	Title           string                     `json:"title"`
}

// CreateTodoRequestPriority defines model for CreateTodoRequest.Priority.
type CreateTodoRequestPriority string

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string  `json:"code"`
		Hint    *string `json:"hint,omitempty"`
		Message string  `json:"message"`
	} `json:"error"`
}

// Me defines model for Me.
type Me struct {
	Active bool   `json:"active"`
	Handle string `json:"handle"`
	Role   string `json:"role"`
}

// Todo defines model for Todo.
type Todo struct {
	// AssigneeId References a user (any role).
	AssigneeId *string   `json:"assigneeId"`
	CreatedAt  time.Time `json:"createdAt"`

	// CreatedBy milestone-4: replaces `ownerId` — attribution only, never access-scoping (GOAL.md).
	CreatedBy string        `json:"createdBy"`
	DueDate   *time.Time    `json:"dueDate"`
	Id        string        `json:"id"`
	Priority  *TodoPriority `json:"priority"`

	// Status milestone-4: replaces `done`. Fixed enum, not an owner-editable table (GOAL.md).
	Status    TodoStatus `json:"status"`
	Title     string     `json:"title"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

// TodoPriority defines model for Todo.Priority.
type TodoPriority string

// TodoStatus milestone-4: replaces `done`. Fixed enum, not an owner-editable table (GOAL.md).
type TodoStatus string

// TodoEvent defines model for TodoEvent.
type TodoEvent struct {
	ActorId string `json:"actorId"`

	// Body The comment text for `type: commented`, `null` otherwise. Rendered client-side through a Markdown-to-React-elements path, never raw HTML (I8's mirror, GOAL.md).
	Body            *string   `json:"body,omitempty"`
	ClientRequestId string    `json:"clientRequestId"`
	CreatedAt       time.Time `json:"createdAt"`
	Id              string    `json:"id"`

	// Payload JSON, shape depends on `type` — `{from, to}` pairs for `status_changed`/`assigned`, `{field, from, to}` for `field_changed`, `null` for `commented`.
	Payload *map[string]interface{} `json:"payload,omitempty"`
	Seq     int64                   `json:"seq"`
	TodoId  string                  `json:"todoId"`

	// Type `created` | `commented` | `status_changed` | `assigned` | `field_changed` — the full read-side vocabulary (DATA_MODEL.md). `created` only ever appears here as a read value, never as something `POST .../events` accepted (I16).
	Type string `json:"type"`
}

// TodoEventList defines model for TodoEventList.
type TodoEventList struct {
	Events []TodoEvent `json:"events"`
}

// TodoList defines model for TodoList.
type TodoList struct {
	Todos []Todo `json:"todos"`
}

// UpdateTodoRequest milestone-4: `title` only — see `updateTodo`'s own description for why `status`/`assigneeId`/`priority`/`dueDate` aren't here. `additionalProperties: false` so a stray `done` is a `validation_error`, not silently dropped.
type UpdateTodoRequest struct {
	// ClientRequestId I19's idempotency key — this endpoint now funnels through the same single write path (I15) as every other mutation.
	ClientRequestId string `json:"clientRequestId"`
	Title           string `json:"title"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoRequest

// CreateTodoEventJSONRequestBody defines body for CreateTodoEvent for application/json ContentType.
type CreateTodoEventJSONRequestBody = CreateTodoEventRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListKeys List the caller's own non-revoked API keys.
	// (GET /keys)
	ListKeys(c *gin.Context)
	// RevokeKey Revoke one of the caller's own API keys.
	// (DELETE /keys/{id})
	RevokeKey(c *gin.Context, id string)
	// GetMe Return the authenticated actor's own identity.
	// (GET /me)
	GetMe(c *gin.Context)
	// ListTodos List every todo.
	// (GET /todos)
	ListTodos(c *gin.Context)
	// CreateTodo Create a todo, attributed to the caller.
	// (POST /todos)
	CreateTodo(c *gin.Context)
	// GetTodo Get a todo by id.
	// (GET /todos/{id})
	GetTodo(c *gin.Context, id string)
	// UpdateTodo Rename a todo.
	// (PATCH /todos/{id})
	UpdateTodo(c *gin.Context, id string)
	// ListTodoEvents This todo's own timeline.
	// (GET /todos/{id}/events)
	ListTodoEvents(c *gin.Context, id string)
	// CreateTodoEvent Append an event to this todo's timeline (I15's single write path).
	// (POST /todos/{id}/events)
	CreateTodoEvent(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListKeys operation middleware
func (siw *ServerInterfaceWrapper) ListKeys(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListKeys(c)
}

// RevokeKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeKey(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeKey(c, id)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// ListTodos operation middleware
func (siw *ServerInterfaceWrapper) ListTodos(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTodos(c)
}

// CreateTodo operation middleware
func (siw *ServerInterfaceWrapper) CreateTodo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTodo(c)
}

// GetTodo operation middleware
func (siw *ServerInterfaceWrapper) GetTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTodo(c, id)
}

// UpdateTodo operation middleware
func (siw *ServerInterfaceWrapper) UpdateTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTodo(c, id)
}

// ListTodoEvents operation middleware
func (siw *ServerInterfaceWrapper) ListTodoEvents(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTodoEvents(c, id)
}

// CreateTodoEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateTodoEvent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTodoEvent(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/todos", wrapper.ListTodos)
	router.POST(options.BaseURL+"/todos", wrapper.CreateTodo)
	router.GET(options.BaseURL+"/todos/:id", wrapper.GetTodo)
	router.PATCH(options.BaseURL+"/todos/:id", wrapper.UpdateTodo)
	router.GET(options.BaseURL+"/todos/:id/events", wrapper.ListTodoEvents)
	router.POST(options.BaseURL+"/todos/:id/events", wrapper.CreateTodoEvent)
	router.GET(options.BaseURL+"/keys", wrapper.ListKeys)
	router.DELETE(options.BaseURL+"/keys/:id", wrapper.RevokeKey)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fvvkhs3cn+VrkmqlnQNyV1L57L5bW3rHJ4lrSKtkg8n1w44aHKgnQHmAMxSjG6r8gD5eC+QPEI+OW+j",
	"ypOkuoEhh+RwV5K1vsoXifMPaDS6f92/buz7JDdVbTRq75Lp+8Siq412yBffC/kS/9Kg83SVG+1R809R",
	"16XKhVdGT946o+meywusBP36R4uLZJr8w2Q79CQ8dZMn1hqb3N7epolEl1tV0yDJNLksEGyYDG6UKYVH",
	"B6K9NXKFqBGMhRtRKskzg21KHCe3afLc+D+aRsuHl/K1vtZmpUHJlIQR9At8ITzgO+W8g3njQTl94sEX",
	"CLkoS7QnDgazR/C///43EHOHOscUtPFQo62Uc8ro4fiNpoW81qLxhbHq3/B3WMwzmlwvU6hEuTC2QpkC",
	"vquVpR8Wb8w1/VhZo5cja0rkJSstcq9ucNQ4tJBblKi9EiUvz4kKIWyVxaWwskTnwCxgVai8gLzA/BoW",
	"QpUoYTD7Q1j2bRoXwjZ3XqufcU2/amtqtF4FW8wtCo/ynJVB0gqfTBMpPI68qjBJE7+uMZkmzlull6TN",
	"sBb3KZ8oVvvB7driQr3reXSbJmShpLJk+mf6fPNy2hG5K8svm2nN/C3mnsYPi36qgqPtLvwa1/y/8li5",
	"+/Y6au92M4ewVqwP5OQx+wT5gUW+NNI8uUHtO96/azoXut3n3NygdSDKEhamsZCXCrUf1cZ5MS8RMpoj",
	"I7dt0MEguyKbtiL3k/MXs3ElsyFbTm6Nc6OFwlJ2XXyA4+UYsrmR6wzaFcDCWMhyU1WoPcoshcyb/cfO",
	"C9+4q7wQeok0i3LskoXQMvjkWzMPfugL5SBo8MSl/BYb8kqsoVqPvHDXJw7I7bN5o0p5Xteo5UzXjc9A",
	"GnSgPCgNuZEIVvgCLWGCBgGZ0XixyEAq0l6ltPDGjlulKAcSSzVHKzyWa4ITU6OGYF1BOKEhQ91UWQrO",
	"QPamtao3SQZCSxB6DYanbLTF3Cy1ciiDvsGiyIu9ZdM6pHK18HkRRrD0IlkAEpahRRjMzr4J+7JRRi18",
	"ESUCV2NOLp8Lh6xtQ+bAQpNHp3sWTLt3aEKb/dvME++Ax3d+3OedwbaiUc7YVSuln6Je+iKZnvV8wQZ1",
	"ODffbm2D5w8AFeyPrSk8dFPIvPIlZvBXyGqrjFV+zReywR+Fxyys+GBmbw6n3bXJzbq9sEv0EJ7CQEBG",
	"DjgO1xnQ7of9HI5BOKeW+vDjeB9PHDAwxwCV6aYsM/AGGh1eCeLSbXLPZOptg33i84378I6fHu7L3cjS",
	"ARUhpSLdiPJFx2IWonS4H6yyvnenwO9m5BqCLFCsIZNGYwaDSpXovNE4Opt8PXl04sBiZW4IH2iXGRAE",
	"ZFuwuUIKlFkwcqdK1L5cg7Smrilc9SDXGJ6bFmmyMGy669GDH0phxQn5ea4o0rcuZNEp2YgSlqIeTgFv",
	"0K4hujZ4Iw2Zg/UOMkKE7CCcChokpBdQqWVBFnBNvjiGD7/+54df//vDr//14de/ffif/4guvxLltS+s",
	"aZYFGF2uW7h08BXbo9LLr0Dw1CeutUWx8GRLbXaTgiZBwaH3Si/Z7YUPYvPaCKGCvCKgbaMVhQdRhuXQ",
	"R7VR2oMoLQq5Bie8cguF4fW5VbgYA+WCwq2rCr1dw0r5ArLWwGcym2wdcbJxQ5gjjU6icdxhHFMOFGdQ",
	"bDfsM4fbyIuNAjDUWRTO6CNgtpWDru71ox7I2rXr2dl3Jw6UxKo2HnW+hmtcp2A0y5NFk8jIQnQMVagl",
	"KzHurFMSARcLzD2srKKl0EJbPw0WZ+qggxSc0jmFZSPNFQ/qxkHIq5hrXynJoSl7fnEJz18/fQqvn8/+",
	"+fWTjPaalcShEkq8wZLhP1ivNStQOi8bSRuxldxodEGT94B13Mqj2dq9ym7NgkYg1CSIKs2KZkapmipJ",
	"k0ItiyRNGrukvPqXj0FCgn8ONeJdK/3Xp6f3rGYfKHmQj0PKkK8f5IHYf5uSjt6ctVCBOBw8qNA5sfwI",
	"dOeht+8fyrr3fpCwb0nP8FDwQCM6UsyNKVEwDwrZSq/0RETuFz0OEF9P28n6ZKOQ1CPdjpvvuuxLXKAl",
	"GkcBhKPtgLIwmmo4/hg7/QwuEz/5vieR2ga6x1OwWJeCJMvMSqOdySzwTu+tmjecUxP6t0gu8hydG7nc",
	"1OS0g58uzp+OKzk8ktT8Zg89yq8ewHFDDPtofXHaMIY/qncoOefa5N+syRFKFSJL+HdPVa3UFP2SNFH6",
	"qrZmadG5JE1oaHZ+47Dr8z0gc/CkqeWn2UofJW3hJ6ok7Zp3R/vbDe4a3C6R3cpzzJmYOfb6u7Gz/v3v",
	"ZwiXe5wgEDv6eAo77C8kucyCVsrhGF6ilkhUMLJRDpFt9iPgmbDX0qz0yJvRSxS5H2GJNJxraQ47hxUr",
	"+KfLZ09hMPv2xEGlCN9S2N34z8kAvgQgHPMksS6NkMeT6yDlrqL/9OrieRr5vEQit44SkMhSOWt6v7Cm",
	"SsGb2wxqoazrZdmTNk3jbXkfM+LOp/zRDvva7t8eq79TvVuLc/iXHaUp7b95vFUYpX9LtIGRSXNE/y3b",
	"2aMcmxTmr13B6Gpv3XRrs3K62F3ihqwtmrKk9FIGi7wxuZg3pbBrGPx4fnl+9ezixyfBtnbyp3INAa3r",
	"GoV1IbcVoTwqItffILoDZyr0BSdhLy5eXcJ4PJ6ETC9jwK89l9/OvumH+V4ACboL6k43vpweY4Bdk74T",
	"J/prXkHaj656bVHnvsJXHPiYSP3S0OI/TZh75QhD9onxmvH183nyTnRraxdsQlygRYSs2UyRtfWg7RDs",
	"hqtiveG1k/upl7CoTzyb5Rg+lah/Eg3vY2SfR7GiT3boFGizgkWjNZZuEyw2pNApvSwxECyOEuRBfxiS",
	"vwX6E4pwVeN5FR9FeH5nakFfKr0w/ZHWY1WXwiOZhEZ4+eTVJbjGLkSOR4ofTwLti00b0fiCmHbOZNoQ",
	"FmXnsZvBKpnC9ygsWnjTnJ4+yretA76OgUZoyEStrq5x7TKilCeO4zDtWGi4vHp1MVLONSjhT/96Gamu",
	"M+UNSpivISPEt1qUE8XD+zUZOQPWiN8LSXClpCxxJWzsxczXIPQ6oKbSsSRcYz4FbSBzmDeh8MdejqFy",
	"m5eCcgxGY6OhbmxtHLYM+6JGff5iNgo0+U3Cdu7NNWqoLTrU/k0SOiIOVqYpJaBiE5JN6PRwu2vBtR2y",
	"wnY5UBnZlBg9d3Y2mX09mf2Bm2EOBtk4LxQuJt3q13bvZs//5fzl7Pz55au4hZftOkM9nNYV93PSdgLh",
	"K04Mvtopy2dLpUdbHWbDmCw3vogxJZh2Uq1HrWHB+YtZkiY3aF2wurPx6fiU/ICSZlGrZJo8Gp+OH5GH",
	"C1+wc0/a9scSe9oQT7nnttNpI6Voo0exf0WGQ2qJl1fCw+wVVzVI5t2qGvdo1q0Zxk7YaN74UaM7w4Hz",
	"qizBFWbloKkJ0rYSQC40o6zyoBGlA2sIEYhczb5jsJubJuwoaYvzu2AGnWZEqRx/0lYNY6Am1OMNIJTj",
	"xf9M2kl3u7Zfn55+sd5hpzF1pGd7p+K5O/v49OzYNBu5JzudT24JNlUl7Dqu8+49Pn8xa6e7TYPJTN4r",
	"eRsMpkTfk9y9Qu+gYxbZGC6Y5xEXRpkG1H98+pg9ax/mTedVhp/G5hiKduRQLWzOHrGPxVLkTmWYYIWz",
	"s4mo1eTmbBIQj4yP0E0QhCgHPzydjTh6D7K8khMGvtE1rrNek3jJy/kZ14c28bivjsGL/9xNoo8e3//R",
	"pjm/u6thcg41ZnG4vZ0tJTSwokKP1iXTP79PFAlPCEH8QFSc5sukGxUDV9ia+H4E/YXMpMKjuJJVITEh",
	"sVj7K8HdOQ4jYHGB1oE3oLzDctGm92GXtdlmFHwywItrdCB0sBwegtORvg38Cf0zfEiHfobHHLkbv2UQ",
	"84u470v0jdUbwNubIm53G9yiB28y7t7d2Ulx+VXuYQpisEz6TVliHgJVJOsnLni3K1RNARTLLbby9s0e",
	"0caVRi8Dzyq5JWGCP0tTCaXHEJbSIgHNnLY9GwosJCVqya3bRtdiqTQvdLB1/G0SftiG+MHom9CqcDGc",
	"vm16kO9YKLhknT2g6WwIUo8BPdlo5MtBPu6OWZu+gwjZpk4VmES5Euvgt5ukMDgtKX5b82QKvLCmCm0n",
	"I9eUzgdTCEd4Pr1kuu0ERil2Onihq9Xbz6mtkU2OjtGD52jLVjXmaqG43sh0X3Je0PZ5Om165TtlgkLU",
	"NWoXenB39ovGkO3Rhgwqhiv+cEOZ/O6hiMOygnIkzHfDKdck6tDGVBQag8dwp9pIExBxQxliE7Dtewot",
	"42+C0ZCMa1z1Wfy2nRyBH53/PlYRv4i1H/arb3eZF8WY2wN3O/ui7nY06eo0iqPDnd7vcJ3jfF/AR4OC",
	"Yss43bgLS9UBrS6ib5Ky+2E9OH9PwIBKrEPZa4sPfLzuPvgetol9sznDx11ObfzVghKULN0J4m8SPvkW",
	"Uj2iasIhlLjwNG50WVD+SBTfWOYDgvEx6/gtMPzbkrqf0EeDIEKt5ANlb8wP8+K+zKBN3sKpnt1aT+Bw",
	"sV1OZhArZVzs/vjKVzwlBNY0ftth6MFH7TzZ7OCgYt4pHE/2ysbDeBatt/I0mZ19OwRfGIdhge6kc6B0",
	"IhqpfHsGILQ2RO4bURL1QJTjTvltSUk4uZnlIyuxJRaqKVEVw5i4cHbDx936q3YwyAql/RTecNPrTdJW",
	"BjaFvE30JbBXS20sCTOLRZuyZdefUIc7UoHjg1R7dXjejmEKBfIZiIPYxzGsz6O3VdkHCjeHZd+PCje/",
	"D6DEnt/vHW5+K8EkdIlwdBCFJtsWQ28wuiglZSgLZZ2HQWj9ub3ToDVavuRwRCl/qa6RLVXjCp0fha/D",
	"0VYGxQXGk3vHDpPtv7tfUQhMU1Aql80Xi6ytDfz0JBYS5ovFhA87EFAN7+IKT4ICHtiktk2eXtsijh1O",
	"nHlVYak0pmA6qv/7hLGuXLTRrWwPF87MsUPWTE1CZ7ZGu9OS7XQkB+GE9DA97EwOMm/4wbY/ybeOHA+l",
	"N/dAcxBuxGPWwyP2O2478zsnlLmeHI8WDw7DBfOFfU7US2RirYwdODskMp3uJ7Eki7nvI1H7tKlz5O9t",
	"rBh0ksft0epwmno3g5AG+e88Noeu085Kwjm49vDd7onpMZy32zSFcCYki5IxIxUaxJIUESvKXR2SJpqO",
	"pXPI+nbby6qtoTehEC2VLIQEAY9PHw3HMNvyOaOPhb+7KJyxaqm0KONO9fC1u7laaNI+NGHb+dOFvwNr",
	"i63ou6kba/D/TTANf/LAbZFQt4jUag+8OTM9cYdJ2nAc9OHQ3rTI2dgymSax/J3c/nL7fwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
