// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateTodoRequestPriority.
const (
	CreateTodoRequestPriorityHigh   CreateTodoRequestPriority = "high"
	CreateTodoRequestPriorityLow    CreateTodoRequestPriority = "low"
	CreateTodoRequestPriorityMedium CreateTodoRequestPriority = "medium"
	CreateTodoRequestPriorityUrgent CreateTodoRequestPriority = "urgent"
)

// Valid indicates whether the value is a known member of the CreateTodoRequestPriority enum.
func (e CreateTodoRequestPriority) Valid() bool {
	switch e {
	case CreateTodoRequestPriorityHigh:
		return true
	case CreateTodoRequestPriorityLow:
		return true
	case CreateTodoRequestPriorityMedium:
		return true
	case CreateTodoRequestPriorityUrgent:
		return true
	default:
		return false
	}
}

// Defines values for TodoPriority.
const (
	TodoPriorityHigh   TodoPriority = "high"
	TodoPriorityLow    TodoPriority = "low"
	TodoPriorityMedium TodoPriority = "medium"
	TodoPriorityUrgent TodoPriority = "urgent"
)

// Valid indicates whether the value is a known member of the TodoPriority enum.
func (e TodoPriority) Valid() bool {
	switch e {
	case TodoPriorityHigh:
		return true
	case TodoPriorityLow:
		return true
	case TodoPriorityMedium:
		return true
	case TodoPriorityUrgent:
		return true
	default:
		return false
	}
}

// Defines values for TodoStatus.
const (
	Closed     TodoStatus = "closed"
	Done       TodoStatus = "done"
	InProgress TodoStatus = "in_progress"
	Open       TodoStatus = "open"
)

// Valid indicates whether the value is a known member of the TodoStatus enum.
func (e TodoStatus) Valid() bool {
	switch e {
	case Closed:
		return true
	case Done:
		return true
	case InProgress:
		return true
	case Open:
		return true
	default:
		return false
	}
}

// ApiKey defines model for ApiKey.
type ApiKey struct {
	CreatedAt time.Time `json:"createdAt"`
	ExpiresAt time.Time `json:"expiresAt"`
	Id        string    `json:"id"`
	Prefix    string    `json:"prefix"`
}

// ApiKeyList defines model for ApiKeyList.
type ApiKeyList struct {
	Keys []ApiKey `json:"keys"`
}

// CreateTodoEventRequest One shape covers all four client-postable `type` values (`_contract/API.md`) — cross-field validation (e.g. `body` required for `commented`, `to` required for `status_changed`) is the handler's job, not this schema's, the same way my-task's own `buildAppendInput` does it in code rather than a `oneOf` discriminator. `type` is deliberately an open string, not an `enum`, so `"created"` and any other unrecognised value reach the handler's own dispatch and are rejected there (I16) — the same path, not a special case for one string.
type CreateTodoEventRequest struct {
	// Body commented — the comment text.
	Body            *string `json:"body,omitempty"`
	ClientRequestId string  `json:"clientRequestId"`

	// Field field_changed — which field `to` changes: `title` | `priority` | `dueDate`.
	Field *string `json:"field,omitempty"`

	// To status_changed — the target status (a `Todo.status` enum value). assigned — the target assignee's user id, or `null` to unassign.
	To   *string `json:"to,omitempty"`
	Type string  `json:"type"`
}

// CreateTodoRequest `additionalProperties: false` so a stray `done` (milestone-1/2/3's removed field) is a `validation_error`, not silently dropped (`_contract/API.md`). No `status` field: `CreateTodo`'s current service signature (`internal/domain/todo/service.go`'s `CreateInput`) has no way to accept one — every created todo starts `open` regardless of what a caller might ask for. Flagged in task-3's own report as a real gap against `_contract/API.md`'s "optionally status" text, not silently worked around here.
type CreateTodoRequest struct {
	AssigneeId *string `json:"assigneeId,omitempty"`

	// ClientRequestId I19's idempotency key, on the `created` event this endpoint's own side effect writes — required, not optional, since `todo_events.client_request_id` is `NOT NULL UNIQUE` at the schema level for every row including `created` ones.
	ClientRequestId string                     `json:"clientRequestId"`
	DueDate         *time.Time                 `json:"dueDate,omitempty"`
	Priority        *CreateTodoRequestPriority `json:"priority,omitempty"`
	Title           string                     `json:"title"`
}

// CreateTodoRequestPriority defines model for CreateTodoRequest.Priority.
type CreateTodoRequestPriority string

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string  `json:"code"`
		Hint    *string `json:"hint,omitempty"`
		Message string  `json:"message"`
	} `json:"error"`
}

// Me defines model for Me.
type Me struct {
	Active bool   `json:"active"`
	Handle string `json:"handle"`
	Role   string `json:"role"`
}

// Todo defines model for Todo.
type Todo struct {
	// AssigneeId References a user (any role).
	AssigneeId *string   `json:"assigneeId"`
	CreatedAt  time.Time `json:"createdAt"`

	// CreatedBy milestone-4: replaces `ownerId` — attribution only, never access-scoping (GOAL.md).
	CreatedBy string        `json:"createdBy"`
	DueDate   *time.Time    `json:"dueDate"`
	Id        string        `json:"id"`
	Priority  *TodoPriority `json:"priority"`

	// Status milestone-4: replaces `done`. Fixed enum, not an owner-editable table (GOAL.md).
	Status    TodoStatus `json:"status"`
	Title     string     `json:"title"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

// TodoPriority defines model for Todo.Priority.
type TodoPriority string

// TodoStatus milestone-4: replaces `done`. Fixed enum, not an owner-editable table (GOAL.md).
type TodoStatus string

// TodoEvent defines model for TodoEvent.
type TodoEvent struct {
	ActorId string `json:"actorId"`

	// Body The comment text for `type: commented`, `null` otherwise. Rendered client-side through a Markdown-to-React-elements path, never raw HTML (I8's mirror, GOAL.md).
	Body            *string   `json:"body,omitempty"`
	ClientRequestId string    `json:"clientRequestId"`
	CreatedAt       time.Time `json:"createdAt"`
	Id              string    `json:"id"`

	// Payload JSON, shape depends on `type` — `{from, to}` pairs for `status_changed`/`assigned`, `{field, from, to}` for `field_changed`, `null` for `commented`.
	Payload *map[string]interface{} `json:"payload,omitempty"`
	Seq     int64                   `json:"seq"`
	TodoId  string                  `json:"todoId"`

	// Type `created` | `commented` | `status_changed` | `assigned` | `field_changed` — the full read-side vocabulary (DATA_MODEL.md). `created` only ever appears here as a read value, never as something `POST .../events` accepted (I16).
	Type string `json:"type"`
}

// TodoEventList defines model for TodoEventList.
type TodoEventList struct {
	Events []TodoEvent `json:"events"`
}

// TodoList defines model for TodoList.
type TodoList struct {
	Todos []Todo `json:"todos"`
}

// UpdateTodoRequest milestone-4: `title` only — see `updateTodo`'s own description for why `status`/`assigneeId`/`priority`/`dueDate` aren't here. `additionalProperties: false` so a stray `done` is a `validation_error`, not silently dropped.
type UpdateTodoRequest struct {
	// ClientRequestId I19's idempotency key — this endpoint now funnels through the same single write path (I15) as every other mutation.
	ClientRequestId string `json:"clientRequestId"`
	Title           string `json:"title"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoRequest

// CreateTodoEventJSONRequestBody defines body for CreateTodoEvent for application/json ContentType.
type CreateTodoEventJSONRequestBody = CreateTodoEventRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListKeys List the caller's own non-revoked API keys.
	// (GET /keys)
	ListKeys(c *gin.Context)
	// RevokeKey Revoke one of the caller's own API keys.
	// (DELETE /keys/{id})
	RevokeKey(c *gin.Context, id string)
	// GetMe Return the authenticated actor's own identity.
	// (GET /me)
	GetMe(c *gin.Context)
	// ListTodos List every todo.
	// (GET /todos)
	ListTodos(c *gin.Context)
	// CreateTodo Create a todo, attributed to the caller.
	// (POST /todos)
	CreateTodo(c *gin.Context)
	// GetTodo Get a todo by id.
	// (GET /todos/{id})
	GetTodo(c *gin.Context, id string)
	// UpdateTodo Rename a todo.
	// (PATCH /todos/{id})
	UpdateTodo(c *gin.Context, id string)
	// ListTodoEvents This todo's own timeline.
	// (GET /todos/{id}/events)
	ListTodoEvents(c *gin.Context, id string)
	// CreateTodoEvent Append an event to this todo's timeline (I15's single write path).
	// (POST /todos/{id}/events)
	CreateTodoEvent(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListKeys operation middleware
func (siw *ServerInterfaceWrapper) ListKeys(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListKeys(c)
}

// RevokeKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeKey(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeKey(c, id)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// ListTodos operation middleware
func (siw *ServerInterfaceWrapper) ListTodos(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTodos(c)
}

// CreateTodo operation middleware
func (siw *ServerInterfaceWrapper) CreateTodo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTodo(c)
}

// GetTodo operation middleware
func (siw *ServerInterfaceWrapper) GetTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTodo(c, id)
}

// UpdateTodo operation middleware
func (siw *ServerInterfaceWrapper) UpdateTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTodo(c, id)
}

// ListTodoEvents operation middleware
func (siw *ServerInterfaceWrapper) ListTodoEvents(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTodoEvents(c, id)
}

// CreateTodoEvent operation middleware
func (siw *ServerInterfaceWrapper) CreateTodoEvent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTodoEvent(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/todos", wrapper.ListTodos)
	router.POST(options.BaseURL+"/todos", wrapper.CreateTodo)
	router.GET(options.BaseURL+"/todos/:id", wrapper.GetTodo)
	router.PATCH(options.BaseURL+"/todos/:id", wrapper.UpdateTodo)
	router.GET(options.BaseURL+"/todos/:id/events", wrapper.ListTodoEvents)
	router.POST(options.BaseURL+"/todos/:id/events", wrapper.CreateTodoEvent)
	router.GET(options.BaseURL+"/keys", wrapper.ListKeys)
	router.DELETE(options.BaseURL+"/keys/:id", wrapper.RevokeKey)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FvvcttGkn+VLtxVidwCSSl2Ugm/KYmT48a2fLZ892GVEkaYJjERMIOdGYjmeVV1D3FPeE9y1T0DECRB",
	"S06sbN0XmwQBTE//+XX/ukcfk9xUtdGovUvmHxOLrjbaIX/5Xsi3+PcGnadvudEeNX8UdV2qXHhl9Ow3",
	"ZzRdc3mBlaBP/2pxmcyTf5ltXz0Lv7rZC2uNTe7v79NEosutquklyTy5LBBsWAzulCmFRweivTRxhagR",
	"jIU7USrJK4NtSpwm92ny2vifTKPl00v5Xt9qs9agZErCCPoEvhAe8INy3sFN40E5feLBFwi5KEu0Jw5G",
	"i2fwv//9PyBuHOocU9DGQ422Us4po8fTK00bea9F4wtj1X/hn7CZV7S4XqVQiXJpbIUyBfxQK0sfLN6Z",
	"W/qwtkavJtaUyFtWWuRe3eGkcWghtyhReyVK3p4TFUIwlcWVsLJE58AsYV2ovIC8wPwWlkKVKGG0+Dps",
	"+z6NG2GfO6/VL7ihT7U1NVqvgi/mFoVHec7KIGmFT+aJFB4nXlWYpInf1JjME+et0ivSZtiL+5xHFKv9",
	"4HJtcak+DPx0nybkoaSyZP43ery7Oe2J3Jfl125Zc/Mb5p7eHzb9UoVA2934LW74f+Wxcg/ZOmrvvltD",
	"WCs2B3LyO4cE+YFFvjTSvLhD7XvRv+s6F7q1c27u0DoQZQlL01jIS4XaT2rjvLgpETJaI6OwbdDBKLsm",
	"n7Yi97PzN4tpJbMxe05ujXOTpcJS9kN8hNPVFLIbIzcZtDuApbGQ5aaqUHuUWQqZN/s/Oy98467zQugV",
	"0irKcUgWQssQk7+ZmxCHvlAOggZPXMp3sSOvxQaqzcQLd3vigMI+u2lUKc/rGrVc6LrxGUiDDpQHpSE3",
	"EsEKX6AlTNAgIDMaL5YZSEXaq5QW3thpqxTlQGKpbtAKj+WG4MTUqCF4VxBOaMhQN1WWgjOQXbVedZVk",
	"ILQEoTdgeMlGW8zNSiuHMugbLIq82Ns27UMqVwufF+ENlm4kD0DCMrQIo8XZN8EunTJq4YsoEbgacwr5",
	"XDhkbRtyBxaaIjrd82Cy3qELdfbr1olXwOMHPx2KzuBb0SkXHKqV0i9Rr3yRzM8GnmCHOlybL7e+wesH",
	"gAr+x94UfnRzyLzyJWbwD8hqq4xVfsNfZIM/Co9Z2PHByt4cLrvrk92+vbAr9BB+hZGAjAJwGr5nQNYP",
	"9hxPQTinVvrw4XgdTxwwMMcElemmLDPwBhodbgni0mUKz2TubYND4vOFh/COfz20y6eRpQcqQkpFuhHl",
	"m57HLEXpcD9ZZUP3zoHvzSg0BHmg2EAmjcYMRpUq0XmjcXI2+2r27MSBxcrcET6QlRkQBGRbsLlGSpRZ",
	"cHKnStS+3IC0pq4pXQ0g1xRemxZpsvDaOWTbnWYnDvLGWnJqh/ZO5QhkA+EbCrJMaY9Wi3ImTSWUnnkj",
	"zSzeOF3x4/FtAWzGUAgH2jAyeQMiz7H2HH3kDniHdgMRH4BeRj5lvYOMYCU7yMmCgjnUKFCpVUFudEsB",
	"PYWfSrEiH1UaCP8mzyJyWKyNpfu4NhMlrEQNYiWUdh4OVXTi4CoxdbBbuYk+fpVwjO9pem3sLRIcUSkH",
	"hENDYNI6egj/B/14ADJ2/Wpx9t2JAyWxqo1HnW/gFjcpGM3RlUVtZqRcHVMFalkbpX1UiVMSAZdLzD2s",
	"raK6lazRxknYZauDFJzSOaVFI801v9RNg5DXsda9VpJTQ/b64hJev3/5Et6/Xvz7+xcZiFBVhlQFJd5h",
	"yfAbDG/NGpTOy0YqvepJbjS6oMkHwDIi2tFq6UFlt/hIbyDUIogozZpWRqmaKkmTQq2KJE0au6K69tfH",
	"IBHBL0O9+NBK/9Xp6QO72QcqfsnjkCrUywd1GA5fpqQ/WDMWKhTuBz9U6JxYPQJd+dXb+w9l3bs/SDi0",
	"pVd4KHgo43tS3BhTomAeEqqFQemJCDwsenxBvD1tFxuSjYByQLqdMN8N2be4REs0ikCIs92IqiBaajx9",
	"jJ/+Di4RH/l+oJDZJprnc8LHUpBkmVlrtAuZBd7nvVU3Dde0RpebFDQFLSO4cxOXm5qCdvTzxfnLaSXH",
	"R4qKPxyhR/nNEwRuwPpH64vT9hR+Uh9Qcs3T1b+syQlKFRhF+HdPVa3UlOiSNFH6urZmZdG5JE3o1Rz8",
	"xmE/5gdA5uCXppaf5ytDlLCFn6iStO/ePe1vDdx3uF0iuZXnWDAxcxuMd2MXw/YfrtAv92ryQKzo4Tns",
	"sK9QZDILWSuHU3iLWiJRscgGOUX6wppmVYCAV8LeSrPWE28mb1HkfoIl0utcSzM4OKxYw79dvnoJo8W3",
	"Jw4qRfiWwq7hf08F8CUA4VgkiU1phDxe3AYpdxX913cXr9PIpyUSuXRUgESWSPiRfVxaU6XgzX0GtVDW",
	"DbLcWdbyAzLLR65IU+g9yg/tsJ+t/fZY9SfVu/U4h3/fUZrS/pvnW4VRibtCGxiRNEf037KNvZK/K2H+",
	"0ReMvu3tmy51O6cvu1vsyNKyKUsqW2XwyDuTi5umFHYDox/PL8+vX138+CL41k79VG4goHVdo7COa9Ou",
	"BI5cu0N0B85U6Asuwt5cvLuE6XQ6C5VeFkt2bn+dfTMM84MAEnQX1J12sZweY2B9l/4kTgz3nIK0j+46",
	"bVHnocZTfPExkYaloc1/njAPyhFeOSTGe8bX389Td7Jb2ztgF+IGKSJkTbdE1vZjtq/gMFwXm45XdjGN",
	"Cwrwrgcx6zoQICzqEx8oE3wuUf4sGjzEyH4fxYox2aNToM0alo3WWLouWXT9J6f0qsRAsDhLUAR9PaZ4",
	"C/QnNMGqxvMuHkV4/mRqQU8qvTTDmdZjVZfCI7mERnj74t0luMYuRY5Hmg8vAu2LQxPR+AK1VzlPTgxh",
	"UXYepwmskjl8j8Kihavm9PRZvm3d8/eYaISGTNTq+hY3LiNKeeI4D5PFwsDj3buLiXKuQQl//c/LSHWd",
	"Ke9Qws0Gtk0Nxa/3G3JyBqwJ3xeK4EpJWeJa2DgLudmA0JuAmkrHlmyN+Ry0gcxh3oTGG0c5hs5pXgqq",
	"MRiNjYa6sbVx2DLsixr1+ZvFJNDkq4T93Jtb1FBbdKj9VRImEg7WpikloGIXkk2YtPC4acltEfLCdjtQ",
	"GdmUGCN3cTZbfDVbfM3DKAejbJoXCpezfvdpa7vF6/84f7s4f335Lprwst1n6EfTvqI9Z+0kDv7ChcFf",
	"dtri2UrpyVaH2TgWy40vYk4Jrp1Um0nrWHD+ZpGkyR1aF7zubHo6PaU4oKJZ1CqZJ8+mp9NnFOHCFxzc",
	"s3b8sMKBMcBLnnntTLpIKdroSZwfkeOQWuLXa+Fh8Y67GiTzbkOKZySb1g3jJGpy0/hJo3uvA+dVWYIr",
	"zNpBUxOkbSWAXGhGWeVBI0oH1hAiELlafMdgd2OaYFHSFtd3wQ16w4BSOX5EYq66+RzrybIBCOV487+Q",
	"dtLdqelXp6dfbHbXGwwdmZl+UvE8HX1+enZsmU7u2c7kkUdyTVUJu4n7/LSNz98s2uXu0+Ays49K3geH",
	"KdEPFHfv0DvouUU2hQvmecSFUaYB9Z+fPufI2od507uV4aexOYamHQVUC5uLZxxjBBD7sxaCFa7OZqJW",
	"s7uzWUA8cj5CN0EQohz88HIx4ew9yvJKzhj4Jre4yQZd4i1v5xfcHPrE86E+Bm/+9xqJHnr+8EPdcHzX",
	"qmFxTjVmeWjenkkJDayo0KN1yfxvHxNFwhNCED8QFZf5MulnxcAVti6+n0F/JTep8CiuZFUoTEgs1v5a",
	"8HSM0whYXKJ14A0o77BctuV9sLI224qCJ/Ne3KIDoYPn8Cu4HBky4M/oX+FTBvQrPBbI/fwtg5hfJHzf",
	"om+s7gBvb4lo7ja5xQjuKu5B6+yUuHwrzxAFMVgm/aYsMQ+JKpL1Exei2xWqpgSK5RZb2XyLZ2S40uhV",
	"4FmlQrYwx3MYj0whbKVFAlo5bccdlFhIStSSR6eNrsVKad7oaBv42yL8oKCCH4wmdqKMdjGd/tYMIN+x",
	"VHDJOntC1+kI0oADveg08uUgH3ffWZuhgwBZ16cKTKJci02I264oDEFLit/2PJkCL62p+NYbIzdUzgdX",
	"CEdoPr9lup3ERSl2hl+cB4bnObU1ssnRMXrwGm3bqsZcLRX3G5nuS64L2jlPb0yufK9NUIi6Ru3okQfm",
	"RVPI9mhDBhXDFT/YUSa/eyjhsK2gHAnz3XjOPYk6TAAVpcYQMTwpNtIEROwoQ2lRyO3IUGgZPxOMhmJc",
	"43rI47dDzgj86Pz3sYv4Rbz9cF58v8u8KMfcH4Tb2RcNt6NFV2/GGgPu9OGA6x2n+wIxGhTEnIZwsA0X",
	"lqoHWn1E74qyh2E9BP9AwoBKbELba4sPfLztIfget4V9052h4ymnNv56SQVKlu4k8auET56FUo+omnAI",
	"JS49vTeGLCh/JIt3nvmEYHzMO/4IDP+xou5n9NEhiFAr+UTVG/PDvHioMmiLt3CqZrfXEzhcHJeTG8RO",
	"GTe7H9/5iqd0wJrGbycMA/ionSefHR10zHuN49le23gcz4INdp5mi7Nvx+AL4zBs0J30DnTORCOVb88A",
	"hNGGyH3DhyCIl0577bcVFeEUZpaIySiOxEI3JapiHAsXrm74uNlw1w5GWaG0n8MVD72ukrYz0DXyuuxL",
	"YK9W2lgSZhGbNmXLrj+jD3ekA8cHmfb68GyOcQoF8hmIg9zHOWwoordd2SdKN4dt30elmz8HUOLM789O",
	"N3+UYBK6RDg6yEKz7YhhMBldlJIqlKWyzsMojP7c3mnMGi1/5XREJX+pbpE9VeManZ+Ep8PRUgbFJcaT",
	"c8cOc+3fu99RCExTUCmX3SyXWdsb+PlFbCTcLJczPuxAQDX+FFd4ERTwxC61HfIM+hZxbCPNiQOvKiyV",
	"xhRMT/X/nDTWl4sM3cr2dOnMHDvkzNQkTGZrtDsj2d5EchROKI/Tw8nkKPOGf9jOJ/nSkeOZdOceaI7C",
	"hXjMeXzEf6ftZH7nhDD3k+PR3tFhumC+sM+JBolM7JVxAGeHRKY3/SSWZDH3QyRqnzZ1WSUISVmjVzxu",
	"jzaH08y7FYQ0yH9n0R16Tns7Cefg2sN3uyeWp3DemmkO4UxIFiVjRio0iBUpInaU+zokTTQ9T+eU9e12",
	"llVbQ3eGc5pRhxIEPD99Np7CYsvnjD6W/j5F4YxVK6VFGS01wNc+zdXCkPapCdvOnw78E1hbHEV/mrqx",
	"Bv/fJNPwJwc8Fgl9i0it9sCbK9MTd1ikjadBHw7tXYucjS2TeRLb38n9r/f/FwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
