// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// CreateTodoRequest defines model for CreateTodoRequest.
type CreateTodoRequest struct {
	Title string `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string  `json:"code"`
		Hint    *string `json:"hint,omitempty"`
		Message string  `json:"message"`
	} `json:"error"`
}

// Me defines model for Me.
type Me struct {
	Active bool   `json:"active"`
	Handle string `json:"handle"`
	Role   string `json:"role"`
}

// Todo defines model for Todo.
type Todo struct {
	CreatedAt time.Time `json:"createdAt"`
	Done      bool      `json:"done"`
	Id        string    `json:"id"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// TodoList defines model for TodoList.
type TodoList struct {
	Todos []Todo `json:"todos"`
}

// UpdateTodoRequest defines model for UpdateTodoRequest.
type UpdateTodoRequest struct {
	Done  *bool   `json:"done,omitempty"`
	Title *string `json:"title,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetMe Return the authenticated actor's own identity.
	// (GET /me)
	GetMe(c *gin.Context)
	// ListTodos List the caller's own todos.
	// (GET /todos)
	ListTodos(c *gin.Context)
	// CreateTodo Create a todo owned by the caller.
	// (POST /todos)
	CreateTodo(c *gin.Context)
	// DeleteTodo Delete one of the caller's own todos.
	// (DELETE /todos/{id})
	DeleteTodo(c *gin.Context, id string)
	// GetTodo Get one of the caller's own todos.
	// (GET /todos/{id})
	GetTodo(c *gin.Context, id string)
	// UpdateTodo Update one of the caller's own todos.
	// (PATCH /todos/{id})
	UpdateTodo(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// ListTodos operation middleware
func (siw *ServerInterfaceWrapper) ListTodos(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTodos(c)
}

// CreateTodo operation middleware
func (siw *ServerInterfaceWrapper) CreateTodo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTodo(c)
}

// DeleteTodo operation middleware
func (siw *ServerInterfaceWrapper) DeleteTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTodo(c, id)
}

// GetTodo operation middleware
func (siw *ServerInterfaceWrapper) GetTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTodo(c, id)
}

// UpdateTodo operation middleware
func (siw *ServerInterfaceWrapper) UpdateTodo(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTodo(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/me", wrapper.GetMe)
	router.GET(options.BaseURL+"/todos", wrapper.ListTodos)
	router.POST(options.BaseURL+"/todos", wrapper.CreateTodo)
	router.DELETE(options.BaseURL+"/todos/:id", wrapper.DeleteTodo)
	router.GET(options.BaseURL+"/todos/:id", wrapper.GetTodo)
	router.PATCH(options.BaseURL+"/todos/:id", wrapper.UpdateTodo)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFfdctu6EX6VHbQzls9QohT73OjOOXUz6hwnGVtpL44zJkSsRMQglgVAKaxHM32IPmGfpANAfzap45PU",
	"8R0pEYvd/b7db/eB5VRWpFE7y8YPzKCtSFsML2+5uMZ/1midf8tJO9ThkVeVkjl3knT6xZL2v9m8wJL7",
	"pz8bnLMx+1O6N53Gf216aQwZtl6vEybQ5kZW3ggbs2mBYOJlsJSkuEMLfPtT3xa8QiADS66kCDeDqRUO",
	"2Dph78n9lWotfryXn/S9ppUGKRLvDPdP4AruAL9K6yzMagfS6hMHrkDIuVJoTiz0Jmfw33//B/jMos4x",
	"AU0OKjSltFaSPh3cah/IJ81rV5CR/8JXCObKX64XCZRczcmUKBLAr5U0/sHgku79w8qQXvQNKQwhS81z",
	"J5fYry0ayA0K1E5yFcKzvESIUBlccCMUWgs0h1Uh8wLyAvN7mHOpUEBv8nMMe51sAgmc+8UgdzglQQfU",
	"qwxVaJyMtHTSKfQPJf/6K+qFK9j4zXCYsFLq7fsoYa6pkI2ZdUbqRbjGk8lHx8a/bYx83n1Gsy+YOw9C",
	"zFfrVuz+OScRfHlyW8IKGYFr/VGitXzRdeiJi8H0/vu2r0++jx52hXSFbccjjAdezIgU8sDDgmuhusPy",
	"RHje9Y2BzefJ9rIu3zzUHWkNNBAXIYWenNyxMRPcYd/J0ptseSZIHwlHis5Qdjxq/VNX4ttufxK+FGxr",
	"fuNXchDRof1jGflVdjKfBIUH6bC0zxV+yOx6dwE3hjftOggmu9z4FJz83Uo8nvLvrtGnFPfw6XlgSFsw",
	"HJaVV4oTC6QRri9vpmBrM+c5Qi+78+3T8NylFx8ng1JkpwO4XKJpdkLju61vX3lQG1qigexi04FDqx3D",
	"W+QGDdzWw+FZvm934R2z2NQ1ZLySd/fY2AwMrU4sGL6Ce2w2InFz86Evra1RwN/+MQ2HDFpSSxQwayCT",
	"2qHRXKUymHdNdmKB545MP3xXB70rpRAKV9xs9GPWANeNK6RegNTgCmnBVpiPQRNkFvPaeFMQ+IAgLQjM",
	"FTcooECDQBqq2lRkMQErdY7woUJ98XHSV7hEBbdMegl2dI8aKoMWtbtlsYtbWFGtBKB0BRoQdVSnINFz",
	"uSii/m3DgZJErQJMKw2TUTp5k05+DgJuoZcN8kLiPC2lQutIY3+U7rGbvP/7xfXk4v30ZgPhdBvniYUv",
	"NPNxbfBMt9ML/BRE6KfDaaGXLaTu73OYncYseg54HdpxlpVNf0ssuPg4YQlborGRdaPBcDD0BKcKNa8k",
	"G7OzwXBwxhJWcVeEqkjLwPwFujZrsxIz77HPDmnVwIp7FCPYYHCOxoIjkM6imgemuACWtB5V1KIiqV2c",
	"ORy/90OSpoBBMHFiQYoYji/UEPpEsDF7h+4qNOTDAe/NcPhiY8YVHhvrDqtMRDfD2HY+HB0zuvMyfTQS",
	"hVmhLktuGjZm1+hqo0MqO67YkG1LwUE4nO46aCc60aKNyDwa4LypcDaBTSO/4w78adQiDFG1rvhC6uBA",
	"T6CSM59+jHMRIrTbEfxCeum9I21PuzDzIjANDv9A3HZqcwS9dgpeBDx/5ZEUB/sV2a7yoZVGcydFKCKu",
	"VryJtbRrp7GQfNI1LkNV5Fh5TOaGyvDpjEQDvcnodACZF7AMrOPGWZhzZbELh/1MyqJ4onVvSTQvhkF7",
	"6F0/1mlnaly3SDB6URIcJUDke8BmA/3weegPdscXYEtMUBAjQZ4pUTj3/Dks7/RBinXkjkKHbRZ98CTq",
	"25wqv+CEpeV8eB73SfiLP+Ql1XdlZZCLph8NCb/sBdpZgkyTu5v7rTODnuauNlypxrebsiIPiFeXIFOS",
	"q37O/aYFGlGg6Kz1cO2eY49wPm+HED8X31uK/tD584d2i/VjNOLlYeSi+e8VcWeTPcy+X4xPxzsJC9Ud",
	"JOzpeh2LOSzZHrMZuQJM7P+HSOzrPpuTmUkhUGdH5LA718NXqamDWnpl7N6h+wPAVdzwEh0ay8a/PTDp",
	"/fbzDUuY5n68iSvO4waVHCTm6WD/OcxHefFNxQjcwrvL6aCF3n41+UENub37/KGG/Drk2WyPr92Q/z/e",
	"xYw+S71wCM1yy7zaKDZmKa9kuhyx9ef1/wIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
