// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	KeyHash   string       `json:"key_hash"`
	KeyPrefix string       `json:"key_prefix"`
	CreatedAt time.Time    `json:"created_at"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type User struct {
	ID         string         `json:"id"`
	Handle     string         `json:"handle"`
	Role       string         `json:"role"`
	Active     bool           `json:"active"`
	SsoSubject sql.NullString `json:"sso_subject"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}
