// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	// milestone-4: no owner scoping - any authenticated actor may read any
	// todo (Ownership model decision, GOAL.md).
	GetTodoByID(ctx context.Context, id string) (Todo, error)
	// The idempotency lookup (I19): checked at the top of the write path,
	// inside the same transaction as the insert it would otherwise perform.
	// A hit means "return this row unchanged, write nothing."
	GetTodoEventByClientRequestID(ctx context.Context, clientRequestID string) (TodoEvent, error)
	// COALESCE to 0 so a todo with no events yet still returns a usable
	// value (the caller adds 1 unconditionally) instead of NULL/sql.ErrNoRows
	// forcing a special first-event case.
	GetTodoEventMaxSeqByTodoID(ctx context.Context, todoID string) (int64, error)
	// handle is COLLATE NOCASE at the schema level (see migration), so this
	// comparison is case-insensitive without needing an explicit COLLATE here.
	GetUserByHandle(ctx context.Context, handle string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserBySSOSubject(ctx context.Context, ssoSubject sql.NullString) (User, error)
	// Every query in this file is named with a "TodoEvent" prefix on
	// purpose, not just for readability: INVARIANTS.md I15 extends
	// internal/architecture_test.go with a check that only
	// internal/domain/todo's own repo file references the generated
	// *TodoEvent*-named query functions - the name is part of the contract
	// that check matches against, not incidental.
	// The single write path (I15) computes seq as
	// GetTodoEventMaxSeqByTodoID's result + 1 in the same transaction as this
	// insert, and checks GetTodoEventByClientRequestID first (I19). This
	// query only ever appends, never mutates (I17: append-only, no
	// exceptions).
	InsertTodoEvent(ctx context.Context, arg InsertTodoEventParams) (TodoEvent, error)
	ListAPIKeysByOwner(ctx context.Context, userID string) ([]ApiKey, error)
	// The per-todo timeline (`_contract/API.md`'s milestone-4 section):
	// oldest-first, unlike the cross-todo feed below.
	ListTodoEventsByTodoID(ctx context.Context, todoID string) ([]TodoEvent, error)
	// The cross-todo activity feed (`GET /api/bff/activity`,
	// `_contract/API.md`): every event across every todo, newest first,
	// joined to todos (title) and users (actor handle/role, so the caller can
	// mark human vs agent). Cursor-paginated on (created_at, id): the first
	// page passes both cursor columns as NULL; every later page passes the
	// previous page's last row's created_at/id.
	//
	// Explicit column list (not sqlc.embed) and sqlc.arg(limit) (not a bare
	// anonymous placeholder) on purpose, not just style: sqlc.embed was
	// observed to reserve a phantom numbered-placeholder slot ahead of the
	// first sqlc.narg below, which pushed every later placeholder's number
	// one higher than the generated Go function's own argument order
	// accounts for. modernc.org/sqlite binds database/sql's positional args
	// strictly by call order to the SQL text's own numbered placeholders, not
	// by re-deriving numbers from how many args were passed - so a query
	// whose numbering starts one higher than expected silently drops the
	// first bound arg onto an unused slot and leaves the highest-numbered
	// placeholder (LIMIT) with nothing bound to it at all ("missing argument
	// with index N"), rather than erroring at generate time. Keeping every
	// placeholder inside sqlc's own numbering (no bare anonymous placeholder)
	// and avoiding sqlc.embed here keeps the numbering contiguous from the
	// start, matching ListTodoEventsFeedParams field order exactly.
	// (Also: plain ASCII hyphens only in this comment block, never an em
	// dash, immediately above a SELECT line - task-1's own report already
	// found that an em dash there corrupts sqlc v1.31.1's star-expansion byte
	// offsets; this query hit a variant of the same corruption during task-2
	// until this comment's em dashes were replaced.)
	ListTodoEventsFeed(ctx context.Context, arg ListTodoEventsFeedParams) ([]ListTodoEventsFeedRow, error)
	// milestone-4: no owner filter - todos are a shared collection (I3 no
	// longer applies to this domain). Reads every row.
	ListTodos(ctx context.Context) ([]Todo, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error)
	UpdateTodoAssignee(ctx context.Context, arg UpdateTodoAssigneeParams) (Todo, error)
	UpdateTodoDueDate(ctx context.Context, arg UpdateTodoDueDateParams) (Todo, error)
	UpdateTodoPriority(ctx context.Context, arg UpdateTodoPriorityParams) (Todo, error)
	UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) (Todo, error)
	UpdateTodoTitle(ctx context.Context, arg UpdateTodoTitleParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
