// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todos.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at
`

type CreateTodoParams struct {
	ID         string         `json:"id"`
	CreatedBy  string         `json:"created_by"`
	Title      string         `json:"title"`
	Status     string         `json:"status"`
	AssigneeID sql.NullString `json:"assignee_id"`
	Priority   sql.NullString `json:"priority"`
	DueDate    sql.NullTime   `json:"due_date"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.ID,
		arg.CreatedBy,
		arg.Title,
		arg.Status,
		arg.AssigneeID,
		arg.Priority,
		arg.DueDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT
    todos.id, todos.created_by, todos.title, todos.status, todos.assignee_id, todos.priority, todos.due_date, todos.created_at, todos.updated_at,
    users.handle AS assignee_handle
FROM todos
LEFT JOIN users ON users.id = todos.assignee_id
WHERE todos.id = ?
`

type GetTodoByIDRow struct {
	ID             string         `json:"id"`
	CreatedBy      string         `json:"created_by"`
	Title          string         `json:"title"`
	Status         string         `json:"status"`
	AssigneeID     sql.NullString `json:"assignee_id"`
	Priority       sql.NullString `json:"priority"`
	DueDate        sql.NullTime   `json:"due_date"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	AssigneeHandle sql.NullString `json:"assignee_handle"`
}

// milestone-4: no owner scoping - any authenticated actor may read any
// todo (Ownership model decision, GOAL.md).
//
// milestone-4 fix-round (handle-exposure): same LEFT JOIN as ListTodos
// above, same reasoning.
func (q *Queries) GetTodoByID(ctx context.Context, id string) (GetTodoByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, id)
	var i GetTodoByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AssigneeHandle,
	)
	return i, err
}

const getUserHandleByID = `-- name: GetUserHandleByID :one
SELECT id, handle FROM users
WHERE id = ?
`

type GetUserHandleByIDRow struct {
	ID     string `json:"id"`
	Handle string `json:"handle"`
}

// milestone-4 fix-round (handle-exposure): resolves a user id to its
// handle - used both to fill in a freshly created todo's assignee handle
// (CreateTodo's own RETURNING * has no join to piggyback on) and to bake
// a {id, handle} snapshot into the `assigned` event's payload at write
// time (internal/domain/todo/service.go's Append), matching my-task's own
// mustGetAssignee
// (~/gits/my-task/src/server/modules/task/task.service.ts:537-545), which
// resolves a handle at the exact same moment for the exact same reason:
// an immutable historical snapshot, not a live join, so a later handle
// change never rewrites old history. Read-only display lookup, same
// ReadOnlyGrant as this file's own joins above (todos.sql / users) - not
// a new grant.
func (q *Queries) GetUserHandleByID(ctx context.Context, id string) (GetUserHandleByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserHandleByID, id)
	var i GetUserHandleByIDRow
	err := row.Scan(&i.ID, &i.Handle)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT
    todos.id, todos.created_by, todos.title, todos.status, todos.assignee_id, todos.priority, todos.due_date, todos.created_at, todos.updated_at,
    users.handle AS assignee_handle
FROM todos
LEFT JOIN users ON users.id = todos.assignee_id
ORDER BY todos.created_at DESC
`

type ListTodosRow struct {
	ID             string         `json:"id"`
	CreatedBy      string         `json:"created_by"`
	Title          string         `json:"title"`
	Status         string         `json:"status"`
	AssigneeID     sql.NullString `json:"assignee_id"`
	Priority       sql.NullString `json:"priority"`
	DueDate        sql.NullTime   `json:"due_date"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	AssigneeHandle sql.NullString `json:"assignee_handle"`
}

// milestone-4: no owner filter - todos are a shared collection (I3 no
// longer applies to this domain). Reads every row.
//
// milestone-4 fix-round (handle-exposure): LEFT JOIN users for the
// assignee's handle - my-task's own task list/detail views show a plain
// handle (`t.assignee`, `task.queries.ts`'s `assigneeHandle` LEFT JOIN),
// never a bare id, and task-7's report found this repo's own
// `Todo.assigneeId` had no equivalent. LEFT JOIN, not JOIN: assignee_id is
// nullable (an unassigned todo must still be returned, with a null
// handle, not dropped). Explicit column list, not SELECT *, for the same
// star-expansion-safety reason ListTodoEventsFeed's own comment
// (todo_events.sql) gives for its join. Needs its own ReadOnlyGrant
// (dbquery.ReadOnlyGrants: "todos.sql" / "users") - this file owns
// "todos", not "users".
func (q *Queries) ListTodos(ctx context.Context) ([]ListTodosRow, error) {
	rows, err := q.db.QueryContext(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodosRow
	for rows.Next() {
		var i ListTodosRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Title,
			&i.Status,
			&i.AssigneeID,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssigneeHandle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoAssignee = `-- name: UpdateTodoAssignee :one
UPDATE todos
SET assignee_id = ?, updated_at = ?
WHERE id = ?
RETURNING id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at
`

type UpdateTodoAssigneeParams struct {
	AssigneeID sql.NullString `json:"assignee_id"`
	UpdatedAt  time.Time      `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateTodoAssignee(ctx context.Context, arg UpdateTodoAssigneeParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoAssignee, arg.AssigneeID, arg.UpdatedAt, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoDueDate = `-- name: UpdateTodoDueDate :one
UPDATE todos
SET due_date = ?, updated_at = ?
WHERE id = ?
RETURNING id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at
`

type UpdateTodoDueDateParams struct {
	DueDate   sql.NullTime `json:"due_date"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) UpdateTodoDueDate(ctx context.Context, arg UpdateTodoDueDateParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoDueDate, arg.DueDate, arg.UpdatedAt, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoPriority = `-- name: UpdateTodoPriority :one
UPDATE todos
SET priority = ?, updated_at = ?
WHERE id = ?
RETURNING id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at
`

type UpdateTodoPriorityParams struct {
	Priority  sql.NullString `json:"priority"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateTodoPriority(ctx context.Context, arg UpdateTodoPriorityParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoPriority, arg.Priority, arg.UpdatedAt, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoStatus = `-- name: UpdateTodoStatus :one
UPDATE todos
SET status = ?, updated_at = ?
WHERE id = ?
RETURNING id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at
`

type UpdateTodoStatusParams struct {
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoTitle = `-- name: UpdateTodoTitle :one
UPDATE todos
SET title = ?, updated_at = ?
WHERE id = ?
RETURNING id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at
`

type UpdateTodoTitleParams struct {
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateTodoTitle(ctx context.Context, arg UpdateTodoTitleParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoTitle, arg.Title, arg.UpdatedAt, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
