// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todos.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at
`

type CreateTodoParams struct {
	ID         string         `json:"id"`
	CreatedBy  string         `json:"created_by"`
	Title      string         `json:"title"`
	Status     string         `json:"status"`
	AssigneeID sql.NullString `json:"assignee_id"`
	Priority   sql.NullString `json:"priority"`
	DueDate    sql.NullTime   `json:"due_date"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.ID,
		arg.CreatedBy,
		arg.Title,
		arg.Status,
		arg.AssigneeID,
		arg.Priority,
		arg.DueDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at FROM todos
WHERE id = ?
`

// milestone-4: no owner scoping - any authenticated actor may read any
// todo (Ownership model decision, GOAL.md).
func (q *Queries) GetTodoByID(ctx context.Context, id string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at FROM todos
ORDER BY created_at DESC
`

// milestone-4: no owner filter - todos are a shared collection (I3 no
// longer applies to this domain). Reads every row.
func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Title,
			&i.Status,
			&i.AssigneeID,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoAssignee = `-- name: UpdateTodoAssignee :one
UPDATE todos
SET assignee_id = ?, updated_at = ?
WHERE id = ?
RETURNING id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at
`

type UpdateTodoAssigneeParams struct {
	AssigneeID sql.NullString `json:"assignee_id"`
	UpdatedAt  time.Time      `json:"updated_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateTodoAssignee(ctx context.Context, arg UpdateTodoAssigneeParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoAssignee, arg.AssigneeID, arg.UpdatedAt, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoDueDate = `-- name: UpdateTodoDueDate :one
UPDATE todos
SET due_date = ?, updated_at = ?
WHERE id = ?
RETURNING id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at
`

type UpdateTodoDueDateParams struct {
	DueDate   sql.NullTime `json:"due_date"`
	UpdatedAt time.Time    `json:"updated_at"`
	ID        string       `json:"id"`
}

func (q *Queries) UpdateTodoDueDate(ctx context.Context, arg UpdateTodoDueDateParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoDueDate, arg.DueDate, arg.UpdatedAt, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoPriority = `-- name: UpdateTodoPriority :one
UPDATE todos
SET priority = ?, updated_at = ?
WHERE id = ?
RETURNING id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at
`

type UpdateTodoPriorityParams struct {
	Priority  sql.NullString `json:"priority"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateTodoPriority(ctx context.Context, arg UpdateTodoPriorityParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoPriority, arg.Priority, arg.UpdatedAt, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoStatus = `-- name: UpdateTodoStatus :one
UPDATE todos
SET status = ?, updated_at = ?
WHERE id = ?
RETURNING id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at
`

type UpdateTodoStatusParams struct {
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoTitle = `-- name: UpdateTodoTitle :one
UPDATE todos
SET title = ?, updated_at = ?
WHERE id = ?
RETURNING id, created_by, title, status, assignee_id, priority, due_date, created_at, updated_at
`

type UpdateTodoTitleParams struct {
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateTodoTitle(ctx context.Context, arg UpdateTodoTitleParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoTitle, arg.Title, arg.UpdatedAt, arg.ID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Title,
		&i.Status,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
