// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todos.sql

package db

import (
	"context"
	"time"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (id, owner_id, title, done, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, owner_id, title, done, created_at, updated_at
`

type CreateTodoParams struct {
	ID        string    `json:"id"`
	OwnerID   string    `json:"owner_id"`
	Title     string    `json:"title"`
	Done      bool      `json:"done"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.ID,
		arg.OwnerID,
		arg.Title,
		arg.Done,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodoByIDAndOwner = `-- name: DeleteTodoByIDAndOwner :execrows
DELETE FROM todos
WHERE id = ? AND owner_id = ?
`

type DeleteTodoByIDAndOwnerParams struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) DeleteTodoByIDAndOwner(ctx context.Context, arg DeleteTodoByIDAndOwnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTodoByIDAndOwner, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTodoByIDAndOwner = `-- name: GetTodoByIDAndOwner :one
SELECT id, owner_id, title, done, created_at, updated_at FROM todos
WHERE id = ? AND owner_id = ?
`

type GetTodoByIDAndOwnerParams struct {
	ID      string `json:"id"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) GetTodoByIDAndOwner(ctx context.Context, arg GetTodoByIDAndOwnerParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByIDAndOwner, arg.ID, arg.OwnerID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodosByOwner = `-- name: ListTodosByOwner :many
SELECT id, owner_id, title, done, created_at, updated_at FROM todos
WHERE owner_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTodosByOwner(ctx context.Context, ownerID string) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodoByIDAndOwner = `-- name: UpdateTodoByIDAndOwner :one
UPDATE todos
SET title = ?, done = ?, updated_at = ?
WHERE id = ? AND owner_id = ?
RETURNING id, owner_id, title, done, created_at, updated_at
`

type UpdateTodoByIDAndOwnerParams struct {
	Title     string    `json:"title"`
	Done      bool      `json:"done"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
	OwnerID   string    `json:"owner_id"`
}

func (q *Queries) UpdateTodoByIDAndOwner(ctx context.Context, arg UpdateTodoByIDAndOwnerParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodoByIDAndOwner,
		arg.Title,
		arg.Done,
		arg.UpdatedAt,
		arg.ID,
		arg.OwnerID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Title,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
