// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo_events.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getTodoEventByClientRequestID = `-- name: GetTodoEventByClientRequestID :one
SELECT id, todo_id, seq, actor_id, type, payload, body, client_request_id, created_at FROM todo_events
WHERE client_request_id = ?
`

// The idempotency lookup (I19): checked at the top of the write path,
// inside the same transaction as the insert it would otherwise perform.
// A hit means "return this row unchanged, write nothing."
func (q *Queries) GetTodoEventByClientRequestID(ctx context.Context, clientRequestID string) (TodoEvent, error) {
	row := q.db.QueryRowContext(ctx, getTodoEventByClientRequestID, clientRequestID)
	var i TodoEvent
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Seq,
		&i.ActorID,
		&i.Type,
		&i.Payload,
		&i.Body,
		&i.ClientRequestID,
		&i.CreatedAt,
	)
	return i, err
}

const getTodoEventMaxSeqByTodoID = `-- name: GetTodoEventMaxSeqByTodoID :one
SELECT CAST(COALESCE(MAX(seq), 0) AS INTEGER) AS max_seq FROM todo_events
WHERE todo_id = ?
`

// COALESCE to 0 so a todo with no events yet still returns a usable
// value (the caller adds 1 unconditionally) instead of NULL/sql.ErrNoRows
// forcing a special first-event case.
func (q *Queries) GetTodoEventMaxSeqByTodoID(ctx context.Context, todoID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTodoEventMaxSeqByTodoID, todoID)
	var max_seq int64
	err := row.Scan(&max_seq)
	return max_seq, err
}

const insertTodoEvent = `-- name: InsertTodoEvent :one

INSERT INTO todo_events (id, todo_id, seq, actor_id, type, payload, body, client_request_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, todo_id, seq, actor_id, type, payload, body, client_request_id, created_at
`

type InsertTodoEventParams struct {
	ID              string         `json:"id"`
	TodoID          string         `json:"todo_id"`
	Seq             int64          `json:"seq"`
	ActorID         string         `json:"actor_id"`
	Type            string         `json:"type"`
	Payload         sql.NullString `json:"payload"`
	Body            sql.NullString `json:"body"`
	ClientRequestID string         `json:"client_request_id"`
	CreatedAt       time.Time      `json:"created_at"`
}

// Every query in this file is named with a "TodoEvent" prefix on
// purpose, not just for readability: INVARIANTS.md I15 extends
// internal/architecture_test.go with a check that only
// internal/domain/todo's own repo file references the generated
// *TodoEvent*-named query functions - the name is part of the contract
// that check matches against, not incidental.
// The single write path (I15) computes seq as
// GetTodoEventMaxSeqByTodoID's result + 1 in the same transaction as this
// insert, and checks GetTodoEventByClientRequestID first (I19). This
// query only ever appends, never mutates (I17: append-only, no
// exceptions).
func (q *Queries) InsertTodoEvent(ctx context.Context, arg InsertTodoEventParams) (TodoEvent, error) {
	row := q.db.QueryRowContext(ctx, insertTodoEvent,
		arg.ID,
		arg.TodoID,
		arg.Seq,
		arg.ActorID,
		arg.Type,
		arg.Payload,
		arg.Body,
		arg.ClientRequestID,
		arg.CreatedAt,
	)
	var i TodoEvent
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Seq,
		&i.ActorID,
		&i.Type,
		&i.Payload,
		&i.Body,
		&i.ClientRequestID,
		&i.CreatedAt,
	)
	return i, err
}

const listTodoEventsByTodoID = `-- name: ListTodoEventsByTodoID :many
SELECT
    todo_events.id, todo_events.todo_id, todo_events.seq, todo_events.actor_id, todo_events.type, todo_events.payload, todo_events.body, todo_events.client_request_id, todo_events.created_at,
    users.handle AS actor_handle,
    users.role AS actor_role
FROM todo_events
JOIN users ON users.id = todo_events.actor_id
WHERE todo_events.todo_id = ?
ORDER BY todo_events.seq ASC
`

type ListTodoEventsByTodoIDRow struct {
	ID              string         `json:"id"`
	TodoID          string         `json:"todo_id"`
	Seq             int64          `json:"seq"`
	ActorID         string         `json:"actor_id"`
	Type            string         `json:"type"`
	Payload         sql.NullString `json:"payload"`
	Body            sql.NullString `json:"body"`
	ClientRequestID string         `json:"client_request_id"`
	CreatedAt       time.Time      `json:"created_at"`
	ActorHandle     string         `json:"actor_handle"`
	ActorRole       string         `json:"actor_role"`
}

// The per-todo timeline (`_contract/API.md`'s milestone-4 section):
// oldest-first, unlike the cross-todo feed below.
//
// milestone-4 fix-round (handle-exposure): joins users for the actor's
// handle/role, the same shape ListTodoEventsFeed below already carries -
// task-7's own report found this query never had it, leaving the
// per-todo timeline structurally unable to tell human from agent
// (Done-when 6/9) or show a name at all (see TimelineEventRow.tsx's own
// TimelineEventData doc comment, which named this exact gap). Explicit
// column list, not SELECT *, for the same star-expansion-safety reason
// ListTodoEventsFeed's own comment above gives for its join. No new
// ReadOnlyGrant needed - this file already has one for users
// (dbquery.ReadOnlyGrants: "todo_events.sql" / "users"), earned by
// ListTodoEventsFeed's own join.
func (q *Queries) ListTodoEventsByTodoID(ctx context.Context, todoID string) ([]ListTodoEventsByTodoIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listTodoEventsByTodoID, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodoEventsByTodoIDRow
	for rows.Next() {
		var i ListTodoEventsByTodoIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.Seq,
			&i.ActorID,
			&i.Type,
			&i.Payload,
			&i.Body,
			&i.ClientRequestID,
			&i.CreatedAt,
			&i.ActorHandle,
			&i.ActorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoEventsFeed = `-- name: ListTodoEventsFeed :many
SELECT
    todo_events.id, todo_events.todo_id, todo_events.seq, todo_events.actor_id, todo_events.type, todo_events.payload, todo_events.body, todo_events.client_request_id, todo_events.created_at,
    todos.id AS todo_id_ref,
    todos.title AS todo_title,
    users.id AS actor_user_id,
    users.handle AS actor_handle,
    users.role AS actor_role
FROM todo_events
JOIN todos ON todos.id = todo_events.todo_id
JOIN users ON users.id = todo_events.actor_id
WHERE (
    ?1 IS NULL
    OR todo_events.created_at < ?1
    OR (todo_events.created_at = ?1 AND todo_events.id < ?2)
)
ORDER BY todo_events.created_at DESC, todo_events.id DESC
LIMIT ?3
`

type ListTodoEventsFeedParams struct {
	CursorCreatedAt interface{}    `json:"cursor_created_at"`
	CursorID        sql.NullString `json:"cursor_id"`
	Limit           int64          `json:"limit"`
}

type ListTodoEventsFeedRow struct {
	ID              string         `json:"id"`
	TodoID          string         `json:"todo_id"`
	Seq             int64          `json:"seq"`
	ActorID         string         `json:"actor_id"`
	Type            string         `json:"type"`
	Payload         sql.NullString `json:"payload"`
	Body            sql.NullString `json:"body"`
	ClientRequestID string         `json:"client_request_id"`
	CreatedAt       time.Time      `json:"created_at"`
	TodoIDRef       string         `json:"todo_id_ref"`
	TodoTitle       string         `json:"todo_title"`
	ActorUserID     string         `json:"actor_user_id"`
	ActorHandle     string         `json:"actor_handle"`
	ActorRole       string         `json:"actor_role"`
}

// The cross-todo activity feed (`GET /api/bff/activity`,
// `_contract/API.md`): every event across every todo, newest first,
// joined to todos (title) and users (actor handle/role, so the caller can
// mark human vs agent). Cursor-paginated on (created_at, id): the first
// page passes both cursor columns as NULL; every later page passes the
// previous page's last row's created_at/id.
//
// Explicit column list (not sqlc.embed) and sqlc.arg(limit) (not a bare
// anonymous placeholder) on purpose, not just style: sqlc.embed was
// observed to reserve a phantom numbered-placeholder slot ahead of the
// first sqlc.narg below, which pushed every later placeholder's number
// one higher than the generated Go function's own argument order
// accounts for. modernc.org/sqlite binds database/sql's positional args
// strictly by call order to the SQL text's own numbered placeholders, not
// by re-deriving numbers from how many args were passed - so a query
// whose numbering starts one higher than expected silently drops the
// first bound arg onto an unused slot and leaves the highest-numbered
// placeholder (LIMIT) with nothing bound to it at all ("missing argument
// with index N"), rather than erroring at generate time. Keeping every
// placeholder inside sqlc's own numbering (no bare anonymous placeholder)
// and avoiding sqlc.embed here keeps the numbering contiguous from the
// start, matching ListTodoEventsFeedParams field order exactly.
// (Also: plain ASCII only in this comment block, never an em dash or any
// other non-ASCII byte, immediately above a SELECT line - task-1's own
// report found that an em dash there corrupts sqlc v1.31.1's
// star-expansion byte offsets; this query hit a variant of the same
// corruption during task-2 until this comment's em dashes were replaced.
// Wider than em dashes specifically: DLV-1's first real fork hit the
// identical corruption with a section-sign character and with Thai prose
// in a different db/queries/*.sql file. internal/db_queries_ascii_test.go
// is the actual floor now - it fails loudly on any non-ASCII byte
// anywhere under db/queries/, not just here, so this paragraph is
// historical context for why the rule exists, not the only thing
// enforcing it.)
func (q *Queries) ListTodoEventsFeed(ctx context.Context, arg ListTodoEventsFeedParams) ([]ListTodoEventsFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listTodoEventsFeed, arg.CursorCreatedAt, arg.CursorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodoEventsFeedRow
	for rows.Next() {
		var i ListTodoEventsFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.Seq,
			&i.ActorID,
			&i.Type,
			&i.Payload,
			&i.Body,
			&i.ClientRequestID,
			&i.CreatedAt,
			&i.TodoIDRef,
			&i.TodoTitle,
			&i.ActorUserID,
			&i.ActorHandle,
			&i.ActorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
