// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo_events.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getTodoEventByClientRequestID = `-- name: GetTodoEventByClientRequestID :one
SELECT id, todo_id, seq, actor_id, type, payload, body, client_request_id, created_at FROM todo_events
WHERE client_request_id = ?
`

// The idempotency lookup (I19): checked at the top of the write path,
// inside the same transaction as the insert it would otherwise perform.
// A hit means "return this row unchanged, write nothing."
func (q *Queries) GetTodoEventByClientRequestID(ctx context.Context, clientRequestID string) (TodoEvent, error) {
	row := q.db.QueryRowContext(ctx, getTodoEventByClientRequestID, clientRequestID)
	var i TodoEvent
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Seq,
		&i.ActorID,
		&i.Type,
		&i.Payload,
		&i.Body,
		&i.ClientRequestID,
		&i.CreatedAt,
	)
	return i, err
}

const getTodoEventMaxSeqByTodoID = `-- name: GetTodoEventMaxSeqByTodoID :one
SELECT CAST(COALESCE(MAX(seq), 0) AS INTEGER) AS max_seq FROM todo_events
WHERE todo_id = ?
`

// COALESCE to 0 so a todo with no events yet still returns a usable
// value (the caller adds 1 unconditionally) instead of NULL/sql.ErrNoRows
// forcing a special first-event case.
func (q *Queries) GetTodoEventMaxSeqByTodoID(ctx context.Context, todoID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTodoEventMaxSeqByTodoID, todoID)
	var max_seq int64
	err := row.Scan(&max_seq)
	return max_seq, err
}

const insertTodoEvent = `-- name: InsertTodoEvent :one

INSERT INTO todo_events (id, todo_id, seq, actor_id, type, payload, body, client_request_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, todo_id, seq, actor_id, type, payload, body, client_request_id, created_at
`

type InsertTodoEventParams struct {
	ID              string         `json:"id"`
	TodoID          string         `json:"todo_id"`
	Seq             int64          `json:"seq"`
	ActorID         string         `json:"actor_id"`
	Type            string         `json:"type"`
	Payload         sql.NullString `json:"payload"`
	Body            sql.NullString `json:"body"`
	ClientRequestID string         `json:"client_request_id"`
	CreatedAt       time.Time      `json:"created_at"`
}

// Every query in this file is named with a "TodoEvent" prefix on
// purpose, not just for readability: INVARIANTS.md I15 extends
// internal/architecture_test.go with a check that only
// internal/domain/todo's own repo file references the generated
// *TodoEvent*-named query functions - the name is part of the contract
// that check matches against, not incidental.
// The single write path (I15) computes seq as
// GetTodoEventMaxSeqByTodoID's result + 1 in the same transaction as this
// insert, and checks GetTodoEventByClientRequestID first (I19). This
// query only ever appends, never mutates (I17: append-only, no
// exceptions).
func (q *Queries) InsertTodoEvent(ctx context.Context, arg InsertTodoEventParams) (TodoEvent, error) {
	row := q.db.QueryRowContext(ctx, insertTodoEvent,
		arg.ID,
		arg.TodoID,
		arg.Seq,
		arg.ActorID,
		arg.Type,
		arg.Payload,
		arg.Body,
		arg.ClientRequestID,
		arg.CreatedAt,
	)
	var i TodoEvent
	err := row.Scan(
		&i.ID,
		&i.TodoID,
		&i.Seq,
		&i.ActorID,
		&i.Type,
		&i.Payload,
		&i.Body,
		&i.ClientRequestID,
		&i.CreatedAt,
	)
	return i, err
}

const listTodoEventsByTodoID = `-- name: ListTodoEventsByTodoID :many
SELECT id, todo_id, seq, actor_id, type, payload, body, client_request_id, created_at FROM todo_events
WHERE todo_id = ?
ORDER BY seq ASC
`

// The per-todo timeline (`_contract/API.md`'s milestone-4 section):
// oldest-first, unlike the cross-todo feed below.
func (q *Queries) ListTodoEventsByTodoID(ctx context.Context, todoID string) ([]TodoEvent, error) {
	rows, err := q.db.QueryContext(ctx, listTodoEventsByTodoID, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TodoEvent
	for rows.Next() {
		var i TodoEvent
		if err := rows.Scan(
			&i.ID,
			&i.TodoID,
			&i.Seq,
			&i.ActorID,
			&i.Type,
			&i.Payload,
			&i.Body,
			&i.ClientRequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoEventsFeed = `-- name: ListTodoEventsFeed :many
SELECT
    todo_events.id, todo_events.todo_id, todo_events.seq, todo_events.actor_id, todo_events.type, todo_events.payload, todo_events.body, todo_events.client_request_id, todo_events.created_at,
    todos.id AS todo_id_ref,
    todos.title AS todo_title,
    users.id AS actor_user_id,
    users.handle AS actor_handle,
    users.role AS actor_role
FROM todo_events
JOIN todos ON todos.id = todo_events.todo_id
JOIN users ON users.id = todo_events.actor_id
WHERE (
    ?2 IS NULL
    OR todo_events.created_at < ?2
    OR (todo_events.created_at = ?2 AND todo_events.id < ?3)
)
ORDER BY todo_events.created_at DESC, todo_events.id DESC
LIMIT ?
`

type ListTodoEventsFeedParams struct {
	CursorCreatedAt interface{}    `json:"cursor_created_at"`
	CursorID        sql.NullString `json:"cursor_id"`
	Limit           int64          `json:"limit"`
}

type ListTodoEventsFeedRow struct {
	TodoEvent   TodoEvent `json:"todo_event"`
	TodoIDRef   string    `json:"todo_id_ref"`
	TodoTitle   string    `json:"todo_title"`
	ActorUserID string    `json:"actor_user_id"`
	ActorHandle string    `json:"actor_handle"`
	ActorRole   string    `json:"actor_role"`
}

// The cross-todo activity feed (`GET /api/bff/activity`,
// `_contract/API.md`): every event across every todo, newest first,
// joined to todos (title) and users (actor handle/role, so the caller can
// mark human vs agent). Cursor-paginated on (created_at, id): the first
// page passes both cursor columns as NULL; every later page passes the
// previous page's last row's created_at/id.
func (q *Queries) ListTodoEventsFeed(ctx context.Context, arg ListTodoEventsFeedParams) ([]ListTodoEventsFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listTodoEventsFeed, arg.CursorCreatedAt, arg.CursorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodoEventsFeedRow
	for rows.Next() {
		var i ListTodoEventsFeedRow
		if err := rows.Scan(
			&i.TodoEvent.ID,
			&i.TodoEvent.TodoID,
			&i.TodoEvent.Seq,
			&i.TodoEvent.ActorID,
			&i.TodoEvent.Type,
			&i.TodoEvent.Payload,
			&i.TodoEvent.Body,
			&i.TodoEvent.ClientRequestID,
			&i.TodoEvent.CreatedAt,
			&i.TodoIDRef,
			&i.TodoTitle,
			&i.ActorUserID,
			&i.ActorHandle,
			&i.ActorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
