// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, handle, role, active, sso_subject, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, handle, role, active, sso_subject, created_at, updated_at
`

type CreateUserParams struct {
	ID         string         `json:"id"`
	Handle     string         `json:"handle"`
	Role       string         `json:"role"`
	Active     bool           `json:"active"`
	SsoSubject sql.NullString `json:"sso_subject"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Handle,
		arg.Role,
		arg.Active,
		arg.SsoSubject,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Role,
		&i.Active,
		&i.SsoSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT id, handle, role, active, sso_subject, created_at, updated_at FROM users
WHERE handle = ?
`

// handle is COLLATE NOCASE at the schema level (see migration), so this
// comparison is case-insensitive without needing an explicit COLLATE here.
func (q *Queries) GetUserByHandle(ctx context.Context, handle string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByHandle, handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Role,
		&i.Active,
		&i.SsoSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, handle, role, active, sso_subject, created_at, updated_at FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Role,
		&i.Active,
		&i.SsoSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySSOSubject = `-- name: GetUserBySSOSubject :one
SELECT id, handle, role, active, sso_subject, created_at, updated_at FROM users
WHERE sso_subject = ?
`

func (q *Queries) GetUserBySSOSubject(ctx context.Context, ssoSubject sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySSOSubject, ssoSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Role,
		&i.Active,
		&i.SsoSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
